/*
 * Copyright (c) 2013 ARM Limited
 * Copyright (c) 2014-2015 Sven Karlsson
 * Copyright (c) 2019 Yifei Liu
 * Copyright (c) 2020 Barkhausen Institut
 * Copyright (c) 2021 StreamComputing Corp
 * Copyright (c) 2025 University of Athens
 * All rights reserved
 *
 * The license below extends only to copyright in the software and shall
 * not be construed as granting a license to any other intellectual
 * property including but not limited to intellectual property relating
 * to a hardware implementation of the functionality of the software
 * licensed hereunder.  You may use the software subject to the license
 * terms below provided that you ensure that this notice is replicated
 * unmodified and in its entirety in all distributions of the software,
 * modified or unmodified, in source code or in binary form.
 *
 * Copyright (c) 2016 RISC-V Foundation
 * Copyright (c) 2016 The University of Virginia
 * Copyright (c) 2024 University of Rostock
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met: redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer;
 * redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution;
 * neither the name of the copyright holders nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __ARCH_RISCV_REGS_MISC_HH__
#define __ARCH_RISCV_REGS_MISC_HH__

#include <string>
#include <unordered_map>

#include "arch/generic/vec_pred_reg.hh"
#include "arch/generic/vec_reg.hh"
#include "arch/riscv/fault_codes.hh"
#include "arch/riscv/types.hh"
#include "base/bitunion.hh"
#include "base/types.hh"
#include "cpu/reg_class.hh"
#include "debug/MiscRegs.hh"
#include "enums/RiscvType.hh"

namespace gem5
{

namespace RiscvISA
{

enum MiscRegIndex
{
    MISCREG_PRV = 0,
    MISCREG_ISA,
    MISCREG_VENDORID,
    MISCREG_ARCHID,
    MISCREG_IMPID,
    MISCREG_HARTID,
    MISCREG_STATUS,
    MISCREG_IP,
    MISCREG_IE,
    /***************  Meta ISA MiscReg Index Start **************/
    //Abotaleb Meta ISA declarations inside Misc
    MISCREG_METAISA0L,    MISCREG_METAISA0H,
    MISCREG_METAISA1L,    MISCREG_METAISA1H,
    MISCREG_METAISA2L,    MISCREG_METAISA2H,
    MISCREG_METAISA3L,    MISCREG_METAISA3H,
    MISCREG_METAISA4L,    MISCREG_METAISA4H,
    MISCREG_METAISA5L,    MISCREG_METAISA5H,
    MISCREG_METAISA6L,    MISCREG_METAISA6H,
    MISCREG_METAISA7L,    MISCREG_METAISA7H,
    MISCREG_METAISA8L,    MISCREG_METAISA8H,
    MISCREG_METAISA9L,    MISCREG_METAISA9H,
    MISCREG_METAISA10L,    MISCREG_METAISA10H,
    MISCREG_METAISA11L,    MISCREG_METAISA11H,
    MISCREG_METAISA12L,    MISCREG_METAISA12H,
    MISCREG_METAISA13L,    MISCREG_METAISA13H,
    MISCREG_METAISA14L,    MISCREG_METAISA14H,
    MISCREG_METAISA15L,    MISCREG_METAISA15H,
    MISCREG_METAISA16L,    MISCREG_METAISA16H,
    MISCREG_METAISA17L,    MISCREG_METAISA17H,
    MISCREG_METAISA18L,    MISCREG_METAISA18H,
    MISCREG_METAISA19L,    MISCREG_METAISA19H,
    MISCREG_METAISA20L,    MISCREG_METAISA20H,
    MISCREG_METAISA21L,    MISCREG_METAISA21H,
    MISCREG_METAISA22L,    MISCREG_METAISA22H,
    MISCREG_METAISA23L,    MISCREG_METAISA23H,
    MISCREG_METAISA24L,    MISCREG_METAISA24H,
    MISCREG_METAISA25L,    MISCREG_METAISA25H,
    MISCREG_METAISA26L,    MISCREG_METAISA26H,
    MISCREG_METAISA27L,    MISCREG_METAISA27H,
    MISCREG_METAISA28L,    MISCREG_METAISA28H,
    MISCREG_METAISA29L,    MISCREG_METAISA29H,
    MISCREG_METAISA30L,    MISCREG_METAISA30H,
    MISCREG_METAISA31L,    MISCREG_METAISA31H,
    MISCREG_METAISA32L,    MISCREG_METAISA32H,
    MISCREG_METAISA33L,    MISCREG_METAISA33H,
    MISCREG_METAISA34L,    MISCREG_METAISA34H,
    MISCREG_METAISA35L,    MISCREG_METAISA35H,
    MISCREG_METAISA36L,    MISCREG_METAISA36H,
    MISCREG_METAISA37L,    MISCREG_METAISA37H,
    MISCREG_METAISA38L,    MISCREG_METAISA38H,
    MISCREG_METAISA39L,    MISCREG_METAISA39H,
    MISCREG_METAISA40L,    MISCREG_METAISA40H,
    MISCREG_METAISA41L,    MISCREG_METAISA41H,
    MISCREG_METAISA42L,    MISCREG_METAISA42H,
    MISCREG_METAISA43L,    MISCREG_METAISA43H,
    MISCREG_METAISA44L,    MISCREG_METAISA44H,
    MISCREG_METAISA45L,    MISCREG_METAISA45H,
    MISCREG_METAISA46L,    MISCREG_METAISA46H,
    MISCREG_METAISA47L,    MISCREG_METAISA47H,
    MISCREG_METAISA48L,    MISCREG_METAISA48H,
    MISCREG_METAISA49L,    MISCREG_METAISA49H,
    MISCREG_METAISA50L,    MISCREG_METAISA50H,
    MISCREG_METAISA51L,    MISCREG_METAISA51H,
    MISCREG_METAISA52L,    MISCREG_METAISA52H,
    MISCREG_METAISA53L,    MISCREG_METAISA53H,
    MISCREG_METAISA54L,    MISCREG_METAISA54H,
    MISCREG_METAISA55L,    MISCREG_METAISA55H,
    MISCREG_METAISA56L,    MISCREG_METAISA56H,
    MISCREG_METAISA57L,    MISCREG_METAISA57H,
    MISCREG_METAISA58L,    MISCREG_METAISA58H,
    MISCREG_METAISA59L,    MISCREG_METAISA59H,
    MISCREG_METAISA60L,    MISCREG_METAISA60H,
    MISCREG_METAISA61L,    MISCREG_METAISA61H,
    MISCREG_METAISA62L,    MISCREG_METAISA62H,
    MISCREG_METAISA63L,    MISCREG_METAISA63H,
    MISCREG_METAISA64L,    MISCREG_METAISA64H,
    MISCREG_METAISA65L,    MISCREG_METAISA65H,
    MISCREG_METAISA66L,    MISCREG_METAISA66H,
    MISCREG_METAISA67L,    MISCREG_METAISA67H,
    MISCREG_METAISA68L,    MISCREG_METAISA68H,
    MISCREG_METAISA69L,    MISCREG_METAISA69H,
    MISCREG_METAISA70L,    MISCREG_METAISA70H,
    MISCREG_METAISA71L,    MISCREG_METAISA71H,
    MISCREG_METAISA72L,    MISCREG_METAISA72H,
    MISCREG_METAISA73L,    MISCREG_METAISA73H,
    MISCREG_METAISA74L,    MISCREG_METAISA74H,
    MISCREG_METAISA75L,    MISCREG_METAISA75H,
    MISCREG_METAISA76L,    MISCREG_METAISA76H,
    MISCREG_METAISA77L,    MISCREG_METAISA77H,
    MISCREG_METAISA78L,    MISCREG_METAISA78H,
    MISCREG_METAISA79L,    MISCREG_METAISA79H,
    MISCREG_METAISA80L,    MISCREG_METAISA80H,
    MISCREG_METAISA81L,    MISCREG_METAISA81H,
    MISCREG_METAISA82L,    MISCREG_METAISA82H,
    MISCREG_METAISA83L,    MISCREG_METAISA83H,
    MISCREG_METAISA84L,    MISCREG_METAISA84H,
    MISCREG_METAISA85L,    MISCREG_METAISA85H,
    MISCREG_METAISA86L,    MISCREG_METAISA86H,
    MISCREG_METAISA87L,    MISCREG_METAISA87H,
    MISCREG_METAISA88L,    MISCREG_METAISA88H,
    MISCREG_METAISA89L,    MISCREG_METAISA89H,
    MISCREG_METAISA90L,    MISCREG_METAISA90H,
    MISCREG_METAISA91L,    MISCREG_METAISA91H,
    MISCREG_METAISA92L,    MISCREG_METAISA92H,
    MISCREG_METAISA93L,    MISCREG_METAISA93H,
    MISCREG_METAISA94L,    MISCREG_METAISA94H,
    MISCREG_METAISA95L,    MISCREG_METAISA95H,
    MISCREG_METAISA96L,    MISCREG_METAISA96H,
    MISCREG_METAISA97L,    MISCREG_METAISA97H,
    MISCREG_METAISA98L,    MISCREG_METAISA98H,
    MISCREG_METAISA99L,    MISCREG_METAISA99H,
    MISCREG_METAISA100L,    MISCREG_METAISA100H,
    /***************  Meta ISA MiscReg Index End   **************/
    MISCREG_CYCLE,
    MISCREG_TIME,
    MISCREG_INSTRET,
    MISCREG_HPMCOUNTER03,
    MISCREG_HPMCOUNTER04,
    MISCREG_HPMCOUNTER05,
    MISCREG_HPMCOUNTER06,
    MISCREG_HPMCOUNTER07,
    MISCREG_HPMCOUNTER08,
    MISCREG_HPMCOUNTER09,
    MISCREG_HPMCOUNTER10,
    MISCREG_HPMCOUNTER11,
    MISCREG_HPMCOUNTER12,
    MISCREG_HPMCOUNTER13,
    MISCREG_HPMCOUNTER14,
    MISCREG_HPMCOUNTER15,
    MISCREG_HPMCOUNTER16,
    MISCREG_HPMCOUNTER17,
    MISCREG_HPMCOUNTER18,
    MISCREG_HPMCOUNTER19,
    MISCREG_HPMCOUNTER20,
    MISCREG_HPMCOUNTER21,
    MISCREG_HPMCOUNTER22,
    MISCREG_HPMCOUNTER23,
    MISCREG_HPMCOUNTER24,
    MISCREG_HPMCOUNTER25,
    MISCREG_HPMCOUNTER26,
    MISCREG_HPMCOUNTER27,
    MISCREG_HPMCOUNTER28,
    MISCREG_HPMCOUNTER29,
    MISCREG_HPMCOUNTER30,
    MISCREG_HPMCOUNTER31,
    MISCREG_HPMEVENT03,
    MISCREG_HPMEVENT04,
    MISCREG_HPMEVENT05,
    MISCREG_HPMEVENT06,
    MISCREG_HPMEVENT07,
    MISCREG_HPMEVENT08,
    MISCREG_HPMEVENT09,
    MISCREG_HPMEVENT10,
    MISCREG_HPMEVENT11,
    MISCREG_HPMEVENT12,
    MISCREG_HPMEVENT13,
    MISCREG_HPMEVENT14,
    MISCREG_HPMEVENT15,
    MISCREG_HPMEVENT16,
    MISCREG_HPMEVENT17,
    MISCREG_HPMEVENT18,
    MISCREG_HPMEVENT19,
    MISCREG_HPMEVENT20,
    MISCREG_HPMEVENT21,
    MISCREG_HPMEVENT22,
    MISCREG_HPMEVENT23,
    MISCREG_HPMEVENT24,
    MISCREG_HPMEVENT25,
    MISCREG_HPMEVENT26,
    MISCREG_HPMEVENT27,
    MISCREG_HPMEVENT28,
    MISCREG_HPMEVENT29,
    MISCREG_HPMEVENT30,
    MISCREG_HPMEVENT31,
    MISCREG_TSELECT,
    MISCREG_TDATA1,
    MISCREG_TDATA2,
    MISCREG_TDATA3,
    MISCREG_DCSR,
    MISCREG_DPC,
    MISCREG_DSCRATCH,

    MISCREG_MEDELEG,
    MISCREG_MIDELEG,
    MISCREG_MTVEC,
    MISCREG_MCOUNTEREN,
    MISCREG_MSCRATCH,
    MISCREG_MEPC,
    MISCREG_MCAUSE,
    MISCREG_MTVAL,
    MISCREG_PMPCFG0,
    MISCREG_PMPCFG1,     // pmpcfg1 is rv32 only
    MISCREG_PMPCFG2,
    MISCREG_PMPCFG3,     // pmpcfg3 is rv32 only
    MISCREG_PMPADDR00,
    MISCREG_PMPADDR01,
    MISCREG_PMPADDR02,
    MISCREG_PMPADDR03,
    MISCREG_PMPADDR04,
    MISCREG_PMPADDR05,
    MISCREG_PMPADDR06,
    MISCREG_PMPADDR07,
    MISCREG_PMPADDR08,
    MISCREG_PMPADDR09,
    MISCREG_PMPADDR10,
    MISCREG_PMPADDR11,
    MISCREG_PMPADDR12,
    MISCREG_PMPADDR13,
    MISCREG_PMPADDR14,
    MISCREG_PMPADDR15,

    MISCREG_RESERVED01, // MISCREG_SEDELEG,
    MISCREG_RESERVED02, // MISCREG_SIDELEG,
    MISCREG_STVEC,
    MISCREG_SCOUNTEREN,
    MISCREG_SSCRATCH,
    MISCREG_SEPC,
    MISCREG_SCAUSE,
    MISCREG_STVAL,
    MISCREG_SATP,
    MISCREG_SENVCFG,

    MISCREG_RESERVED03, // MISCREG_UTVEC,
    MISCREG_RESERVED04, // MISCREG_USCRATCH,
    MISCREG_RESERVED05, // MISCREG_UEPC,
    MISCREG_RESERVED06, // MISCREG_UCAUSE,
    MISCREG_RESERVED07, // MISCREG_UTVAL,
    MISCREG_FFLAGS,
    MISCREG_FRM,

    MISCREG_VSTART,
    MISCREG_VXSAT,
    MISCREG_VXRM,
    MISCREG_VCSR,
    MISCREG_VL,
    MISCREG_VTYPE,
    MISCREG_VLENB,

    // H-extension registers (RV64)

    MISCREG_HVIP, // vssi bit is alias for mip.vssi

    MISCREG_MTINST,
    MISCREG_MTVAL2,

    MISCREG_HSTATUS,
    MISCREG_HEDELEG,
    MISCREG_HIDELEG,
    MISCREG_HCOUNTEREN,
    MISCREG_HGEIE,
    MISCREG_HTVAL,
    MISCREG_HTINST,
    MISCREG_HGEIP,

    MISCREG_HENVCFG,
    MISCREG_HGATP,
    MISCREG_HCONTEXT,
    MISCREG_HTIMEDELTA,

    MISCREG_VSSTATUS,
    MISCREG_VSTVEC,
    MISCREG_VSSCRATCH,
    MISCREG_VSEPC,
    MISCREG_VSCAUSE,
    MISCREG_VSTVAL,
    MISCREG_VSATP,

    // This register stores the V-bit.
    // It is not mandated by the specification,
    // however it is useful for the implementation.
    MISCREG_VIRT,

    // H-extension registers end here

    // These registers are not in the standard, hence does not exist in the
    // CSRData map. These are mainly used to provide a minimal implementation
    // for non-maskable-interrupt in our simple cpu.
    // non-maskable-interrupt-vector-base-address: NMI version of xTVEC
    MISCREG_NMIVEC,
    // non-maskable-interrupt-enable: NMI version of xIE
    MISCREG_NMIE,
    // non-maskable-interrupt-pending: NMI version of xIP
    MISCREG_NMIP,

    // Resumable Non-Maskable Interrupts
    MISCREG_MNSCRATCH,
    MISCREG_MNEPC,
    MISCREG_MNCAUSE,
    MISCREG_MNSTATUS,

    // the following MicsRegIndex are RV32 only
    MISCREG_MSTATUSH,

    MISCREG_CYCLEH,
    MISCREG_TIMEH,
    MISCREG_INSTRETH,
    MISCREG_HPMCOUNTER03H,
    MISCREG_HPMCOUNTER04H,
    MISCREG_HPMCOUNTER05H,
    MISCREG_HPMCOUNTER06H,
    MISCREG_HPMCOUNTER07H,
    MISCREG_HPMCOUNTER08H,
    MISCREG_HPMCOUNTER09H,
    MISCREG_HPMCOUNTER10H,
    MISCREG_HPMCOUNTER11H,
    MISCREG_HPMCOUNTER12H,
    MISCREG_HPMCOUNTER13H,
    MISCREG_HPMCOUNTER14H,
    MISCREG_HPMCOUNTER15H,
    MISCREG_HPMCOUNTER16H,
    MISCREG_HPMCOUNTER17H,
    MISCREG_HPMCOUNTER18H,
    MISCREG_HPMCOUNTER19H,
    MISCREG_HPMCOUNTER20H,
    MISCREG_HPMCOUNTER21H,
    MISCREG_HPMCOUNTER22H,
    MISCREG_HPMCOUNTER23H,
    MISCREG_HPMCOUNTER24H,
    MISCREG_HPMCOUNTER25H,
    MISCREG_HPMCOUNTER26H,
    MISCREG_HPMCOUNTER27H,
    MISCREG_HPMCOUNTER28H,
    MISCREG_HPMCOUNTER29H,
    MISCREG_HPMCOUNTER30H,
    MISCREG_HPMCOUNTER31H,
    MISCREG_JVT,

    NUM_PHYS_MISCREGS,
    MISCREG_FFLAGS_EXE = NUM_PHYS_MISCREGS,

    NUM_MISCREGS
};

inline constexpr RegClass miscRegClass(MiscRegClass, MiscRegClassName,
        NUM_MISCREGS, debug::MiscRegs);

enum CSRIndex
{
    /***************  Meta ISA CSR Addresses Start **************/
    //[Abotaleb] MetaISA CSR Registers Address Declaration
    CSR_METAISA0L = 0x800,    CSR_METAISA0H = 0x801,
    CSR_METAISA1L = 0x802,    CSR_METAISA1H = 0x803,
    CSR_METAISA2L = 0x804,    CSR_METAISA2H = 0x805,
    CSR_METAISA3L = 0x806,    CSR_METAISA3H = 0x807,
    CSR_METAISA4L = 0x808,    CSR_METAISA4H = 0x809,
    CSR_METAISA5L = 0x80a,    CSR_METAISA5H = 0x80b,
    CSR_METAISA6L = 0x80c,    CSR_METAISA6H = 0x80d,
    CSR_METAISA7L = 0x80e,    CSR_METAISA7H = 0x80f,
    CSR_METAISA8L = 0x810,    CSR_METAISA8H = 0x811,
    CSR_METAISA9L = 0x812,    CSR_METAISA9H = 0x813,
    CSR_METAISA10L = 0x814,    CSR_METAISA10H = 0x815,
    CSR_METAISA11L = 0x816,    CSR_METAISA11H = 0x817,
    CSR_METAISA12L = 0x818,    CSR_METAISA12H = 0x819,
    CSR_METAISA13L = 0x81a,    CSR_METAISA13H = 0x81b,
    CSR_METAISA14L = 0x81c,    CSR_METAISA14H = 0x81d,
    CSR_METAISA15L = 0x81e,    CSR_METAISA15H = 0x81f,
    CSR_METAISA16L = 0x820,    CSR_METAISA16H = 0x821,
    CSR_METAISA17L = 0x822,    CSR_METAISA17H = 0x823,
    CSR_METAISA18L = 0x824,    CSR_METAISA18H = 0x825,
    CSR_METAISA19L = 0x826,    CSR_METAISA19H = 0x827,
    CSR_METAISA20L = 0x828,    CSR_METAISA20H = 0x829,
    CSR_METAISA21L = 0x82a,    CSR_METAISA21H = 0x82b,
    CSR_METAISA22L = 0x82c,    CSR_METAISA22H = 0x82d,
    CSR_METAISA23L = 0x82e,    CSR_METAISA23H = 0x82f,
    CSR_METAISA24L = 0x830,    CSR_METAISA24H = 0x831,
    CSR_METAISA25L = 0x832,    CSR_METAISA25H = 0x833,
    CSR_METAISA26L = 0x834,    CSR_METAISA26H = 0x835,
    CSR_METAISA27L = 0x836,    CSR_METAISA27H = 0x837,
    CSR_METAISA28L = 0x838,    CSR_METAISA28H = 0x839,
    CSR_METAISA29L = 0x83a,    CSR_METAISA29H = 0x83b,
    CSR_METAISA30L = 0x83c,    CSR_METAISA30H = 0x83d,
    CSR_METAISA31L = 0x83e,    CSR_METAISA31H = 0x83f,
    CSR_METAISA32L = 0x840,    CSR_METAISA32H = 0x841,
    CSR_METAISA33L = 0x842,    CSR_METAISA33H = 0x843,
    CSR_METAISA34L = 0x844,    CSR_METAISA34H = 0x845,
    CSR_METAISA35L = 0x846,    CSR_METAISA35H = 0x847,
    CSR_METAISA36L = 0x848,    CSR_METAISA36H = 0x849,
    CSR_METAISA37L = 0x84a,    CSR_METAISA37H = 0x84b,
    CSR_METAISA38L = 0x84c,    CSR_METAISA38H = 0x84d,
    CSR_METAISA39L = 0x84e,    CSR_METAISA39H = 0x84f,
    CSR_METAISA40L = 0x850,    CSR_METAISA40H = 0x851,
    CSR_METAISA41L = 0x852,    CSR_METAISA41H = 0x853,
    CSR_METAISA42L = 0x854,    CSR_METAISA42H = 0x855,
    CSR_METAISA43L = 0x856,    CSR_METAISA43H = 0x857,
    CSR_METAISA44L = 0x858,    CSR_METAISA44H = 0x859,
    CSR_METAISA45L = 0x85a,    CSR_METAISA45H = 0x85b,
    CSR_METAISA46L = 0x85c,    CSR_METAISA46H = 0x85d,
    CSR_METAISA47L = 0x85e,    CSR_METAISA47H = 0x85f,
    CSR_METAISA48L = 0x860,    CSR_METAISA48H = 0x861,
    CSR_METAISA49L = 0x862,    CSR_METAISA49H = 0x863,
    CSR_METAISA50L = 0x864,    CSR_METAISA50H = 0x865,
    CSR_METAISA51L = 0x866,    CSR_METAISA51H = 0x867,
    CSR_METAISA52L = 0x868,    CSR_METAISA52H = 0x869,
    CSR_METAISA53L = 0x86a,    CSR_METAISA53H = 0x86b,
    CSR_METAISA54L = 0x86c,    CSR_METAISA54H = 0x86d,
    CSR_METAISA55L = 0x86e,    CSR_METAISA55H = 0x86f,
    CSR_METAISA56L = 0x870,    CSR_METAISA56H = 0x871,
    CSR_METAISA57L = 0x872,    CSR_METAISA57H = 0x873,
    CSR_METAISA58L = 0x874,    CSR_METAISA58H = 0x875,
    CSR_METAISA59L = 0x876,    CSR_METAISA59H = 0x877,
    CSR_METAISA60L = 0x878,    CSR_METAISA60H = 0x879,
    CSR_METAISA61L = 0x87a,    CSR_METAISA61H = 0x87b,
    CSR_METAISA62L = 0x87c,    CSR_METAISA62H = 0x87d,
    CSR_METAISA63L = 0x87e,    CSR_METAISA63H = 0x87f,
    CSR_METAISA64L = 0x880,    CSR_METAISA64H = 0x881,
    CSR_METAISA65L = 0x882,    CSR_METAISA65H = 0x883,
    CSR_METAISA66L = 0x884,    CSR_METAISA66H = 0x885,
    CSR_METAISA67L = 0x886,    CSR_METAISA67H = 0x887,
    CSR_METAISA68L = 0x888,    CSR_METAISA68H = 0x889,
    CSR_METAISA69L = 0x88a,    CSR_METAISA69H = 0x88b,
    CSR_METAISA70L = 0x88c,    CSR_METAISA70H = 0x88d,
    CSR_METAISA71L = 0x88e,    CSR_METAISA71H = 0x88f,
    CSR_METAISA72L = 0x890,    CSR_METAISA72H = 0x891,
    CSR_METAISA73L = 0x892,    CSR_METAISA73H = 0x893,
    CSR_METAISA74L = 0x894,    CSR_METAISA74H = 0x895,
    CSR_METAISA75L = 0x896,    CSR_METAISA75H = 0x897,
    CSR_METAISA76L = 0x898,    CSR_METAISA76H = 0x899,
    CSR_METAISA77L = 0x89a,    CSR_METAISA77H = 0x89b,
    CSR_METAISA78L = 0x89c,    CSR_METAISA78H = 0x89d,
    CSR_METAISA79L = 0x89e,    CSR_METAISA79H = 0x89f,
    CSR_METAISA80L = 0x8a0,    CSR_METAISA80H = 0x8a1,
    CSR_METAISA81L = 0x8a2,    CSR_METAISA81H = 0x8a3,
    CSR_METAISA82L = 0x8a4,    CSR_METAISA82H = 0x8a5,
    CSR_METAISA83L = 0x8a6,    CSR_METAISA83H = 0x8a7,
    CSR_METAISA84L = 0x8a8,    CSR_METAISA84H = 0x8a9,
    CSR_METAISA85L = 0x8aa,    CSR_METAISA85H = 0x8ab,
    CSR_METAISA86L = 0x8ac,    CSR_METAISA86H = 0x8ad,
    CSR_METAISA87L = 0x8ae,    CSR_METAISA87H = 0x8af,
    CSR_METAISA88L = 0x8b0,    CSR_METAISA88H = 0x8b1,
    CSR_METAISA89L = 0x8b2,    CSR_METAISA89H = 0x8b3,
    CSR_METAISA90L = 0x8b4,    CSR_METAISA90H = 0x8b5,
    CSR_METAISA91L = 0x8b6,    CSR_METAISA91H = 0x8b7,
    CSR_METAISA92L = 0x8b8,    CSR_METAISA92H = 0x8b9,
    CSR_METAISA93L = 0x8ba,    CSR_METAISA93H = 0x8bb,
    CSR_METAISA94L = 0x8bc,    CSR_METAISA94H = 0x8bd,
    CSR_METAISA95L = 0x8be,    CSR_METAISA95H = 0x8bf,
    CSR_METAISA96L = 0x8c0,    CSR_METAISA96H = 0x8c1,
    CSR_METAISA97L = 0x8c2,    CSR_METAISA97H = 0x8c3,
    CSR_METAISA98L = 0x8c4,    CSR_METAISA98H = 0x8c5,
    CSR_METAISA99L = 0x8c6,    CSR_METAISA99H = 0x8c7,
    CSR_METAISA100L = 0x8c8,    CSR_METAISA100H = 0x8c9,
    /***************  Meta ISA CSR Addresses End **************/
    CSR_FFLAGS = 0x001,
    CSR_FRM = 0x002,
    CSR_FCSR = 0x003,
    CSR_CYCLE = 0xC00,
    CSR_TIME = 0xC01,
    CSR_INSTRET = 0xC02,
    CSR_HPMCOUNTER03 = 0xC03,
    CSR_HPMCOUNTER04 = 0xC04,
    CSR_HPMCOUNTER05 = 0xC05,
    CSR_HPMCOUNTER06 = 0xC06,
    CSR_HPMCOUNTER07 = 0xC07,
    CSR_HPMCOUNTER08 = 0xC08,
    CSR_HPMCOUNTER09 = 0xC09,
    CSR_HPMCOUNTER10 = 0xC0A,
    CSR_HPMCOUNTER11 = 0xC0B,
    CSR_HPMCOUNTER12 = 0xC0C,
    CSR_HPMCOUNTER13 = 0xC0D,
    CSR_HPMCOUNTER14 = 0xC0E,
    CSR_HPMCOUNTER15 = 0xC0F,
    CSR_HPMCOUNTER16 = 0xC10,
    CSR_HPMCOUNTER17 = 0xC11,
    CSR_HPMCOUNTER18 = 0xC12,
    CSR_HPMCOUNTER19 = 0xC13,
    CSR_HPMCOUNTER20 = 0xC14,
    CSR_HPMCOUNTER21 = 0xC15,
    CSR_HPMCOUNTER22 = 0xC16,
    CSR_HPMCOUNTER23 = 0xC17,
    CSR_HPMCOUNTER24 = 0xC18,
    CSR_HPMCOUNTER25 = 0xC19,
    CSR_HPMCOUNTER26 = 0xC1A,
    CSR_HPMCOUNTER27 = 0xC1B,
    CSR_HPMCOUNTER28 = 0xC1C,
    CSR_HPMCOUNTER29 = 0xC1D,
    CSR_HPMCOUNTER30 = 0xC1E,
    CSR_HPMCOUNTER31 = 0xC1F,

    // rv32 only csr register begin
    CSR_CYCLEH = 0xC80,
    CSR_TIMEH = 0xC81,
    CSR_INSTRETH = 0xC82,
    CSR_HPMCOUNTER03H = 0xC83,
    CSR_HPMCOUNTER04H = 0xC84,
    CSR_HPMCOUNTER05H = 0xC85,
    CSR_HPMCOUNTER06H = 0xC86,
    CSR_HPMCOUNTER07H = 0xC87,
    CSR_HPMCOUNTER08H = 0xC88,
    CSR_HPMCOUNTER09H = 0xC89,
    CSR_HPMCOUNTER10H = 0xC8A,
    CSR_HPMCOUNTER11H = 0xC8B,
    CSR_HPMCOUNTER12H = 0xC8C,
    CSR_HPMCOUNTER13H = 0xC8D,
    CSR_HPMCOUNTER14H = 0xC8E,
    CSR_HPMCOUNTER15H = 0xC8F,
    CSR_HPMCOUNTER16H = 0xC90,
    CSR_HPMCOUNTER17H = 0xC91,
    CSR_HPMCOUNTER18H = 0xC92,
    CSR_HPMCOUNTER19H = 0xC93,
    CSR_HPMCOUNTER20H = 0xC94,
    CSR_HPMCOUNTER21H = 0xC95,
    CSR_HPMCOUNTER22H = 0xC96,
    CSR_HPMCOUNTER23H = 0xC97,
    CSR_HPMCOUNTER24H = 0xC98,
    CSR_HPMCOUNTER25H = 0xC99,
    CSR_HPMCOUNTER26H = 0xC9A,
    CSR_HPMCOUNTER27H = 0xC9B,
    CSR_HPMCOUNTER28H = 0xC9C,
    CSR_HPMCOUNTER29H = 0xC9D,
    CSR_HPMCOUNTER30H = 0xC9E,
    CSR_HPMCOUNTER31H = 0xC9F,
    // rv32 only csr register end

    CSR_SSTATUS = 0x100,
    CSR_SIE = 0x104,
    CSR_STVEC = 0x105,
    CSR_SCOUNTEREN = 0x106,
    CSR_SSCRATCH = 0x140,
    CSR_SEPC = 0x141,
    CSR_SCAUSE = 0x142,
    CSR_STVAL = 0x143,
    CSR_SIP = 0x144,
    CSR_SATP = 0x180,
    CSR_SENVCFG = 0x10A, // 20240411 RISCV spec, volume 2

    CSR_MVENDORID = 0xF11,
    CSR_MARCHID = 0xF12,
    CSR_MIMPID = 0xF13,
    CSR_MHARTID = 0xF14,
    CSR_MSTATUS = 0x300,
    CSR_MISA = 0x301,
    CSR_MEDELEG = 0x302,
    CSR_MIDELEG = 0x303,
    CSR_MIE = 0x304,
    CSR_MTVEC = 0x305,
    CSR_MCOUNTEREN = 0x306,
    CSR_MSTATUSH = 0x310, // rv32 only
    CSR_MSCRATCH = 0x340,
    CSR_MEPC = 0x341,
    CSR_MCAUSE = 0x342,
    CSR_MTVAL = 0x343,
    CSR_MIP = 0x344,
    CSR_PMPCFG0 = 0x3A0,
    CSR_PMPCFG1 = 0x3A1, // pmpcfg1 rv32 only
    CSR_PMPCFG2 = 0x3A2,
    CSR_PMPCFG3 = 0x3A3,// pmpcfg3 rv32 only
    CSR_PMPADDR00 = 0x3B0,
    CSR_PMPADDR01 = 0x3B1,
    CSR_PMPADDR02 = 0x3B2,
    CSR_PMPADDR03 = 0x3B3,
    CSR_PMPADDR04 = 0x3B4,
    CSR_PMPADDR05 = 0x3B5,
    CSR_PMPADDR06 = 0x3B6,
    CSR_PMPADDR07 = 0x3B7,
    CSR_PMPADDR08 = 0x3B8,
    CSR_PMPADDR09 = 0x3B9,
    CSR_PMPADDR10 = 0x3BA,
    CSR_PMPADDR11 = 0x3BB,
    CSR_PMPADDR12 = 0x3BC,
    CSR_PMPADDR13 = 0x3BD,
    CSR_PMPADDR14 = 0x3BE,
    CSR_PMPADDR15 = 0x3BF,
    CSR_MCYCLE = 0xB00,
    CSR_MINSTRET = 0xB02,
    CSR_MHPMCOUNTER03 = 0xB03,
    CSR_MHPMCOUNTER04 = 0xB04,
    CSR_MHPMCOUNTER05 = 0xB05,
    CSR_MHPMCOUNTER06 = 0xB06,
    CSR_MHPMCOUNTER07 = 0xB07,
    CSR_MHPMCOUNTER08 = 0xB08,
    CSR_MHPMCOUNTER09 = 0xB09,
    CSR_MHPMCOUNTER10 = 0xB0A,
    CSR_MHPMCOUNTER11 = 0xB0B,
    CSR_MHPMCOUNTER12 = 0xB0C,
    CSR_MHPMCOUNTER13 = 0xB0D,
    CSR_MHPMCOUNTER14 = 0xB0E,
    CSR_MHPMCOUNTER15 = 0xB0F,
    CSR_MHPMCOUNTER16 = 0xB10,
    CSR_MHPMCOUNTER17 = 0xB11,
    CSR_MHPMCOUNTER18 = 0xB12,
    CSR_MHPMCOUNTER19 = 0xB13,
    CSR_MHPMCOUNTER20 = 0xB14,
    CSR_MHPMCOUNTER21 = 0xB15,
    CSR_MHPMCOUNTER22 = 0xB16,
    CSR_MHPMCOUNTER23 = 0xB17,
    CSR_MHPMCOUNTER24 = 0xB18,
    CSR_MHPMCOUNTER25 = 0xB19,
    CSR_MHPMCOUNTER26 = 0xB1A,
    CSR_MHPMCOUNTER27 = 0xB1B,
    CSR_MHPMCOUNTER28 = 0xB1C,
    CSR_MHPMCOUNTER29 = 0xB1D,
    CSR_MHPMCOUNTER30 = 0xB1E,
    CSR_MHPMCOUNTER31 = 0xB1F,

    // rv32 only csr register begin
    CSR_MCYCLEH = 0xB80,
    CSR_MINSTRETH = 0xB82,
    CSR_MHPMCOUNTER03H = 0xB83,
    CSR_MHPMCOUNTER04H = 0xB84,
    CSR_MHPMCOUNTER05H = 0xB85,
    CSR_MHPMCOUNTER06H = 0xB86,
    CSR_MHPMCOUNTER07H = 0xB87,
    CSR_MHPMCOUNTER08H = 0xB88,
    CSR_MHPMCOUNTER09H = 0xB89,
    CSR_MHPMCOUNTER10H = 0xB8A,
    CSR_MHPMCOUNTER11H = 0xB8B,
    CSR_MHPMCOUNTER12H = 0xB8C,
    CSR_MHPMCOUNTER13H = 0xB8D,
    CSR_MHPMCOUNTER14H = 0xB8E,
    CSR_MHPMCOUNTER15H = 0xB8F,
    CSR_MHPMCOUNTER16H = 0xB90,
    CSR_MHPMCOUNTER17H = 0xB91,
    CSR_MHPMCOUNTER18H = 0xB92,
    CSR_MHPMCOUNTER19H = 0xB93,
    CSR_MHPMCOUNTER20H = 0xB94,
    CSR_MHPMCOUNTER21H = 0xB95,
    CSR_MHPMCOUNTER22H = 0xB96,
    CSR_MHPMCOUNTER23H = 0xB97,
    CSR_MHPMCOUNTER24H = 0xB98,
    CSR_MHPMCOUNTER25H = 0xB99,
    CSR_MHPMCOUNTER26H = 0xB9A,
    CSR_MHPMCOUNTER27H = 0xB9B,
    CSR_MHPMCOUNTER28H = 0xB9C,
    CSR_MHPMCOUNTER29H = 0xB9D,
    CSR_MHPMCOUNTER30H = 0xB9E,
    CSR_MHPMCOUNTER31H = 0xB9F,
    // rv32 only csr register end

    CSR_MHPMEVENT03 = 0x323,
    CSR_MHPMEVENT04 = 0x324,
    CSR_MHPMEVENT05 = 0x325,
    CSR_MHPMEVENT06 = 0x326,
    CSR_MHPMEVENT07 = 0x327,
    CSR_MHPMEVENT08 = 0x328,
    CSR_MHPMEVENT09 = 0x329,
    CSR_MHPMEVENT10 = 0x32A,
    CSR_MHPMEVENT11 = 0x32B,
    CSR_MHPMEVENT12 = 0x32C,
    CSR_MHPMEVENT13 = 0x32D,
    CSR_MHPMEVENT14 = 0x32E,
    CSR_MHPMEVENT15 = 0x32F,
    CSR_MHPMEVENT16 = 0x330,
    CSR_MHPMEVENT17 = 0x331,
    CSR_MHPMEVENT18 = 0x332,
    CSR_MHPMEVENT19 = 0x333,
    CSR_MHPMEVENT20 = 0x334,
    CSR_MHPMEVENT21 = 0x335,
    CSR_MHPMEVENT22 = 0x336,
    CSR_MHPMEVENT23 = 0x337,
    CSR_MHPMEVENT24 = 0x338,
    CSR_MHPMEVENT25 = 0x339,
    CSR_MHPMEVENT26 = 0x33A,
    CSR_MHPMEVENT27 = 0x33B,
    CSR_MHPMEVENT28 = 0x33C,
    CSR_MHPMEVENT29 = 0x33D,
    CSR_MHPMEVENT30 = 0x33E,
    CSR_MHPMEVENT31 = 0x33F,

    CSR_TSELECT = 0x7A0,
    CSR_TDATA1 = 0x7A1,
    CSR_TDATA2 = 0x7A2,
    CSR_TDATA3 = 0x7A3,
    CSR_DCSR = 0x7B0,
    CSR_DPC = 0x7B1,
    CSR_DSCRATCH = 0x7B2,

    CSR_VSTART       = 0x008,
    CSR_VXSAT        = 0x009,
    CSR_VXRM         = 0x00A,
    CSR_VCSR         = 0x00F,
    CSR_VL           = 0xC20,
    CSR_VTYPE        = 0xC21,
    CSR_VLENB        = 0xC22,

    CSR_MNSCRATCH    = 0x740,
    CSR_MNEPC        = 0x741,
    CSR_MNCAUSE      = 0x742,
    CSR_MNSTATUS     = 0x744,

    CSR_JVT          = 0x017,

    // H-extension (RV64) CSRs

    CSR_MTINST = 0x34A,
    CSR_MTVAL2 = 0x34B,

    CSR_HSTATUS = 0x600,
    CSR_HEDELEG = 0x602,
    CSR_HIDELEG = 0x603,
    CSR_HIE = 0x604,
    CSR_HTIMEDELTA = 0x605,
    CSR_HCOUNTEREN = 0x606,
    CSR_HGEIE = 0x607,

    CSR_HTVAL = 0x643,
    CSR_HIP = 0x644,
    CSR_HVIP = 0x645,
    CSR_HTINST = 0x64A,
    CSR_HGEIP = 0xE12,

    CSR_HENVCFG = 0x60A,
    CSR_HGATP = 0x680,
    CSR_HCONTEXT = 0x6A8,

    CSR_VSSTATUS  = 0x200,
    CSR_VSIE      = 0x204,
    CSR_VSTVEC    = 0x205,
    CSR_VSSCRATCH = 0x240,
    CSR_VSEPC     = 0x241,
    CSR_VSCAUSE   = 0x242,
    CSR_VSTVAL    = 0x243,
    CSR_VSIP      = 0x244,
    CSR_VSATP     = 0x280

    // H-extension (RV64) CSRs end here
};

struct CSRMetadata
{
    const std::string name;
    const int physIndex;
    const uint64_t rvTypes;
    const uint64_t isaExts;
    const bool requireSmrnmi = false;
};

template <typename... T>
constexpr uint64_t rvTypeFlags(T... args) {
    return ((1 << args) | ...);
}

template <typename... T>
constexpr uint64_t isaExtsFlags(T... isa_exts) {
    return ((1ULL << (isa_exts - 'a')) | ...);
}

constexpr uint64_t isaExtsFlags() {
    return 0ULL;
}

const std::unordered_map<int, CSRMetadata> CSRData = {
    /***************  Meta ISA CSR Meta Data Start **************/
    //[Abotaleb] MetaISA CSR Registers Map Declaration
    {CSR_METAISA0L , {"meta_0l", MISCREG_METAISA0L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA0H , {"meta_0h", MISCREG_METAISA0H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA1L , {"meta_1l", MISCREG_METAISA1L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA1H , {"meta_1h", MISCREG_METAISA1H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA2L , {"meta_2l", MISCREG_METAISA2L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA2H , {"meta_2h", MISCREG_METAISA2H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA3L , {"meta_3l", MISCREG_METAISA3L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA3H , {"meta_3h", MISCREG_METAISA3H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA4L , {"meta_4l", MISCREG_METAISA4L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA4H , {"meta_4h", MISCREG_METAISA4H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA5L , {"meta_5l", MISCREG_METAISA5L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA5H , {"meta_5h", MISCREG_METAISA5H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA6L , {"meta_6l", MISCREG_METAISA6L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA6H , {"meta_6h", MISCREG_METAISA6H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA7L , {"meta_7l", MISCREG_METAISA7L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA7H , {"meta_7h", MISCREG_METAISA7H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA8L , {"meta_8l", MISCREG_METAISA8L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA8H , {"meta_8h", MISCREG_METAISA8H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA9L , {"meta_9l", MISCREG_METAISA9L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA9H , {"meta_9h", MISCREG_METAISA9H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA10L , {"meta_10l", MISCREG_METAISA10L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA10H , {"meta_10h", MISCREG_METAISA10H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA11L , {"meta_11l", MISCREG_METAISA11L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA11H , {"meta_11h", MISCREG_METAISA11H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA12L , {"meta_12l", MISCREG_METAISA12L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA12H , {"meta_12h", MISCREG_METAISA12H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA13L , {"meta_13l", MISCREG_METAISA13L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA13H , {"meta_13h", MISCREG_METAISA13H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA14L , {"meta_14l", MISCREG_METAISA14L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA14H , {"meta_14h", MISCREG_METAISA14H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA15L , {"meta_15l", MISCREG_METAISA15L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA15H , {"meta_15h", MISCREG_METAISA15H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA16L , {"meta_16l", MISCREG_METAISA16L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA16H , {"meta_16h", MISCREG_METAISA16H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA17L , {"meta_17l", MISCREG_METAISA17L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA17H , {"meta_17h", MISCREG_METAISA17H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA18L , {"meta_18l", MISCREG_METAISA18L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA18H , {"meta_18h", MISCREG_METAISA18H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA19L , {"meta_19l", MISCREG_METAISA19L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA19H , {"meta_19h", MISCREG_METAISA19H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA20L , {"meta_20l", MISCREG_METAISA20L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA20H , {"meta_20h", MISCREG_METAISA20H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA21L , {"meta_21l", MISCREG_METAISA21L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA21H , {"meta_21h", MISCREG_METAISA21H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA22L , {"meta_22l", MISCREG_METAISA22L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA22H , {"meta_22h", MISCREG_METAISA22H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA23L , {"meta_23l", MISCREG_METAISA23L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA23H , {"meta_23h", MISCREG_METAISA23H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA24L , {"meta_24l", MISCREG_METAISA24L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA24H , {"meta_24h", MISCREG_METAISA24H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA25L , {"meta_25l", MISCREG_METAISA25L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA25H , {"meta_25h", MISCREG_METAISA25H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA26L , {"meta_26l", MISCREG_METAISA26L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA26H , {"meta_26h", MISCREG_METAISA26H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA27L , {"meta_27l", MISCREG_METAISA27L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA27H , {"meta_27h", MISCREG_METAISA27H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA28L , {"meta_28l", MISCREG_METAISA28L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA28H , {"meta_28h", MISCREG_METAISA28H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA29L , {"meta_29l", MISCREG_METAISA29L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA29H , {"meta_29h", MISCREG_METAISA29H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA30L , {"meta_30l", MISCREG_METAISA30L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA30H , {"meta_30h", MISCREG_METAISA30H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA31L , {"meta_31l", MISCREG_METAISA31L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA31H , {"meta_31h", MISCREG_METAISA31H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA32L , {"meta_32l", MISCREG_METAISA32L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA32H , {"meta_32h", MISCREG_METAISA32H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA33L , {"meta_33l", MISCREG_METAISA33L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA33H , {"meta_33h", MISCREG_METAISA33H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA34L , {"meta_34l", MISCREG_METAISA34L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA34H , {"meta_34h", MISCREG_METAISA34H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA35L , {"meta_35l", MISCREG_METAISA35L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA35H , {"meta_35h", MISCREG_METAISA35H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA36L , {"meta_36l", MISCREG_METAISA36L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA36H , {"meta_36h", MISCREG_METAISA36H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA37L , {"meta_37l", MISCREG_METAISA37L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA37H , {"meta_37h", MISCREG_METAISA37H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA38L , {"meta_38l", MISCREG_METAISA38L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA38H , {"meta_38h", MISCREG_METAISA38H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA39L , {"meta_39l", MISCREG_METAISA39L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA39H , {"meta_39h", MISCREG_METAISA39H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA40L , {"meta_40l", MISCREG_METAISA40L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA40H , {"meta_40h", MISCREG_METAISA40H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA41L , {"meta_41l", MISCREG_METAISA41L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA41H , {"meta_41h", MISCREG_METAISA41H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA42L , {"meta_42l", MISCREG_METAISA42L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA42H , {"meta_42h", MISCREG_METAISA42H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA43L , {"meta_43l", MISCREG_METAISA43L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA43H , {"meta_43h", MISCREG_METAISA43H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA44L , {"meta_44l", MISCREG_METAISA44L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA44H , {"meta_44h", MISCREG_METAISA44H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA45L , {"meta_45l", MISCREG_METAISA45L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA45H , {"meta_45h", MISCREG_METAISA45H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA46L , {"meta_46l", MISCREG_METAISA46L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA46H , {"meta_46h", MISCREG_METAISA46H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA47L , {"meta_47l", MISCREG_METAISA47L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA47H , {"meta_47h", MISCREG_METAISA47H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA48L , {"meta_48l", MISCREG_METAISA48L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA48H , {"meta_48h", MISCREG_METAISA48H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA49L , {"meta_49l", MISCREG_METAISA49L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA49H , {"meta_49h", MISCREG_METAISA49H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA50L , {"meta_50l", MISCREG_METAISA50L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA50H , {"meta_50h", MISCREG_METAISA50H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA51L , {"meta_51l", MISCREG_METAISA51L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA51H , {"meta_51h", MISCREG_METAISA51H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA52L , {"meta_52l", MISCREG_METAISA52L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA52H , {"meta_52h", MISCREG_METAISA52H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA53L , {"meta_53l", MISCREG_METAISA53L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA53H , {"meta_53h", MISCREG_METAISA53H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA54L , {"meta_54l", MISCREG_METAISA54L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA54H , {"meta_54h", MISCREG_METAISA54H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA55L , {"meta_55l", MISCREG_METAISA55L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA55H , {"meta_55h", MISCREG_METAISA55H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA56L , {"meta_56l", MISCREG_METAISA56L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA56H , {"meta_56h", MISCREG_METAISA56H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA57L , {"meta_57l", MISCREG_METAISA57L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA57H , {"meta_57h", MISCREG_METAISA57H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA58L , {"meta_58l", MISCREG_METAISA58L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA58H , {"meta_58h", MISCREG_METAISA58H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA59L , {"meta_59l", MISCREG_METAISA59L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA59H , {"meta_59h", MISCREG_METAISA59H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA60L , {"meta_60l", MISCREG_METAISA60L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA60H , {"meta_60h", MISCREG_METAISA60H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA61L , {"meta_61l", MISCREG_METAISA61L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA61H , {"meta_61h", MISCREG_METAISA61H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA62L , {"meta_62l", MISCREG_METAISA62L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA62H , {"meta_62h", MISCREG_METAISA62H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA63L , {"meta_63l", MISCREG_METAISA63L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA63H , {"meta_63h", MISCREG_METAISA63H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA64L , {"meta_64l", MISCREG_METAISA64L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA64H , {"meta_64h", MISCREG_METAISA64H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA65L , {"meta_65l", MISCREG_METAISA65L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA65H , {"meta_65h", MISCREG_METAISA65H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA66L , {"meta_66l", MISCREG_METAISA66L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA66H , {"meta_66h", MISCREG_METAISA66H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA67L , {"meta_67l", MISCREG_METAISA67L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA67H , {"meta_67h", MISCREG_METAISA67H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA68L , {"meta_68l", MISCREG_METAISA68L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA68H , {"meta_68h", MISCREG_METAISA68H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA69L , {"meta_69l", MISCREG_METAISA69L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA69H , {"meta_69h", MISCREG_METAISA69H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA70L , {"meta_70l", MISCREG_METAISA70L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA70H , {"meta_70h", MISCREG_METAISA70H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA71L , {"meta_71l", MISCREG_METAISA71L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA71H , {"meta_71h", MISCREG_METAISA71H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA72L , {"meta_72l", MISCREG_METAISA72L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA72H , {"meta_72h", MISCREG_METAISA72H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA73L , {"meta_73l", MISCREG_METAISA73L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA73H , {"meta_73h", MISCREG_METAISA73H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA74L , {"meta_74l", MISCREG_METAISA74L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA74H , {"meta_74h", MISCREG_METAISA74H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA75L , {"meta_75l", MISCREG_METAISA75L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA75H , {"meta_75h", MISCREG_METAISA75H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA76L , {"meta_76l", MISCREG_METAISA76L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA76H , {"meta_76h", MISCREG_METAISA76H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA77L , {"meta_77l", MISCREG_METAISA77L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA77H , {"meta_77h", MISCREG_METAISA77H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA78L , {"meta_78l", MISCREG_METAISA78L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA78H , {"meta_78h", MISCREG_METAISA78H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA79L , {"meta_79l", MISCREG_METAISA79L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA79H , {"meta_79h", MISCREG_METAISA79H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA80L , {"meta_80l", MISCREG_METAISA80L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA80H , {"meta_80h", MISCREG_METAISA80H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA81L , {"meta_81l", MISCREG_METAISA81L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA81H , {"meta_81h", MISCREG_METAISA81H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA82L , {"meta_82l", MISCREG_METAISA82L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA82H , {"meta_82h", MISCREG_METAISA82H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA83L , {"meta_83l", MISCREG_METAISA83L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA83H , {"meta_83h", MISCREG_METAISA83H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA84L , {"meta_84l", MISCREG_METAISA84L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA84H , {"meta_84h", MISCREG_METAISA84H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA85L , {"meta_85l", MISCREG_METAISA85L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA85H , {"meta_85h", MISCREG_METAISA85H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA86L , {"meta_86l", MISCREG_METAISA86L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA86H , {"meta_86h", MISCREG_METAISA86H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA87L , {"meta_87l", MISCREG_METAISA87L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA87H , {"meta_87h", MISCREG_METAISA87H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA88L , {"meta_88l", MISCREG_METAISA88L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA88H , {"meta_88h", MISCREG_METAISA88H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA89L , {"meta_89l", MISCREG_METAISA89L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA89H , {"meta_89h", MISCREG_METAISA89H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA90L , {"meta_90l", MISCREG_METAISA90L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA90H , {"meta_90h", MISCREG_METAISA90H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA91L , {"meta_91l", MISCREG_METAISA91L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA91H , {"meta_91h", MISCREG_METAISA91H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA92L , {"meta_92l", MISCREG_METAISA92L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA92H , {"meta_92h", MISCREG_METAISA92H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA93L , {"meta_93l", MISCREG_METAISA93L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA93H , {"meta_93h", MISCREG_METAISA93H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA94L , {"meta_94l", MISCREG_METAISA94L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA94H , {"meta_94h", MISCREG_METAISA94H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA95L , {"meta_95l", MISCREG_METAISA95L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA95H , {"meta_95h", MISCREG_METAISA95H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA96L , {"meta_96l", MISCREG_METAISA96L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA96H , {"meta_96h", MISCREG_METAISA96H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA97L , {"meta_97l", MISCREG_METAISA97L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA97H , {"meta_97h", MISCREG_METAISA97H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA98L , {"meta_98l", MISCREG_METAISA98L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA98H , {"meta_98h", MISCREG_METAISA98H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA99L , {"meta_99l", MISCREG_METAISA99L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA99H , {"meta_99h", MISCREG_METAISA99H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA100L , {"meta_100l", MISCREG_METAISA100L, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_METAISA100H , {"meta_100h", MISCREG_METAISA100H, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    /***************  Meta ISA CSR Meta Data End  **************/
    {CSR_FFLAGS,
        {"fflags", MISCREG_FFLAGS, rvTypeFlags(RV64, RV32),
         isaExtsFlags('f')}},
    {CSR_FRM,
        {"frm", MISCREG_FRM, rvTypeFlags(RV64, RV32), isaExtsFlags('f')}},
    {CSR_FCSR,
        {"fcsr", MISCREG_FFLAGS, rvTypeFlags(RV64, RV32), isaExtsFlags('f')}},
    {CSR_CYCLE,
        {"cycle", MISCREG_CYCLE, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_TIME,
        {"time", MISCREG_TIME, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_INSTRET,
        {"instret", MISCREG_INSTRET, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_HPMCOUNTER03,
        {"hpmcounter03", MISCREG_HPMCOUNTER03, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER04,
        {"hpmcounter04", MISCREG_HPMCOUNTER04, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER05,
        {"hpmcounter05", MISCREG_HPMCOUNTER05, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER06,
        {"hpmcounter06", MISCREG_HPMCOUNTER06, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER07,
        {"hpmcounter07", MISCREG_HPMCOUNTER07, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER08,
        {"hpmcounter08", MISCREG_HPMCOUNTER08, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER09,
        {"hpmcounter09", MISCREG_HPMCOUNTER09, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER10,
        {"hpmcounter10", MISCREG_HPMCOUNTER10, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER11,
        {"hpmcounter11", MISCREG_HPMCOUNTER11, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER12,
        {"hpmcounter12", MISCREG_HPMCOUNTER12, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER13,
        {"hpmcounter13", MISCREG_HPMCOUNTER13, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER14,
        {"hpmcounter14", MISCREG_HPMCOUNTER14, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER15,
        {"hpmcounter15", MISCREG_HPMCOUNTER15, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER16,
        {"hpmcounter16", MISCREG_HPMCOUNTER16, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER17,
        {"hpmcounter17", MISCREG_HPMCOUNTER17, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER18,
        {"hpmcounter18", MISCREG_HPMCOUNTER18, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER19,
        {"hpmcounter19", MISCREG_HPMCOUNTER19, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER20,
        {"hpmcounter20", MISCREG_HPMCOUNTER20, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER21,
        {"hpmcounter21", MISCREG_HPMCOUNTER21, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER22,
        {"hpmcounter22", MISCREG_HPMCOUNTER22, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER23,
        {"hpmcounter23", MISCREG_HPMCOUNTER23, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER24,
        {"hpmcounter24", MISCREG_HPMCOUNTER24, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER25,
        {"hpmcounter25", MISCREG_HPMCOUNTER25, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER26,
        {"hpmcounter26", MISCREG_HPMCOUNTER26, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER27,
        {"hpmcounter27", MISCREG_HPMCOUNTER27, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER28,
        {"hpmcounter28", MISCREG_HPMCOUNTER28, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER29,
        {"hpmcounter29", MISCREG_HPMCOUNTER29, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER30,
        {"hpmcounter30", MISCREG_HPMCOUNTER30, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER31,
        {"hpmcounter31", MISCREG_HPMCOUNTER31, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_CYCLEH,
        {"cycleh", MISCREG_CYCLEH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_TIMEH,
        {"timeh", MISCREG_TIMEH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_INSTRETH,
        {"instreth", MISCREG_INSTRETH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_HPMCOUNTER03H,
        {"hpmcounter03h", MISCREG_HPMCOUNTER03H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER04H,
        {"hpmcounter04h", MISCREG_HPMCOUNTER04H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER05H,
        {"hpmcounter05h", MISCREG_HPMCOUNTER05H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER06H,
        {"hpmcounter06h", MISCREG_HPMCOUNTER06H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER07H,
        {"hpmcounter07h", MISCREG_HPMCOUNTER07H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER08H,
        {"hpmcounter08h", MISCREG_HPMCOUNTER08H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER09H,
        {"hpmcounter09h", MISCREG_HPMCOUNTER09H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER10H,
        {"hpmcounter10h", MISCREG_HPMCOUNTER10H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER11H,
        {"hpmcounter11h", MISCREG_HPMCOUNTER11H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER12H,
        {"hpmcounter12h", MISCREG_HPMCOUNTER12H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER13H,
        {"hpmcounter13h", MISCREG_HPMCOUNTER13H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER14H,
        {"hpmcounter14h", MISCREG_HPMCOUNTER14H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER15H,
        {"hpmcounter15h", MISCREG_HPMCOUNTER15H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER16H,
        {"hpmcounter16h", MISCREG_HPMCOUNTER16H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER17H,
        {"hpmcounter17h", MISCREG_HPMCOUNTER17H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER18H,
        {"hpmcounter18h", MISCREG_HPMCOUNTER18H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER19H,
        {"hpmcounter19h", MISCREG_HPMCOUNTER19H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER20H,
        {"hpmcounter20h", MISCREG_HPMCOUNTER20H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER21H,
        {"hpmcounter21h", MISCREG_HPMCOUNTER21H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER22H,
        {"hpmcounter22h", MISCREG_HPMCOUNTER22H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER23H,
        {"hpmcounter23h", MISCREG_HPMCOUNTER23H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER24H,
        {"hpmcounter24h", MISCREG_HPMCOUNTER24H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER25H,
        {"hpmcounter25h", MISCREG_HPMCOUNTER25H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER26H,
        {"hpmcounter26h", MISCREG_HPMCOUNTER26H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER27H,
        {"hpmcounter27h", MISCREG_HPMCOUNTER27H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER28H,
        {"hpmcounter28h", MISCREG_HPMCOUNTER28H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER29H,
        {"hpmcounter29h", MISCREG_HPMCOUNTER29H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER30H,
        {"hpmcounter30h", MISCREG_HPMCOUNTER30H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_HPMCOUNTER31H,
        {"hpmcounter31h", MISCREG_HPMCOUNTER31H, rvTypeFlags(RV32),
         isaExtsFlags()}},

    {CSR_SSTATUS,
        {"sstatus", MISCREG_STATUS, rvTypeFlags(RV64, RV32),
         isaExtsFlags('s')}},
    {CSR_SIE,
        {"sie", MISCREG_IE, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_STVEC,
        {"stvec", MISCREG_STVEC, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_SCOUNTEREN,
        {"scounteren", MISCREG_SCOUNTEREN, rvTypeFlags(RV64, RV32),
         isaExtsFlags('s')}},
    {CSR_SSCRATCH,
        {"sscratch", MISCREG_SSCRATCH, rvTypeFlags(RV64, RV32),
         isaExtsFlags('s')}},
    {CSR_SEPC,
        {"sepc", MISCREG_SEPC, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_SCAUSE,
        {"scause", MISCREG_SCAUSE, rvTypeFlags(RV64, RV32),
         isaExtsFlags('s')}},
    {CSR_STVAL,
        {"stval", MISCREG_STVAL, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_SIP,
        {"sip", MISCREG_IP, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_SATP,
        {"satp", MISCREG_SATP, rvTypeFlags(RV64, RV32), isaExtsFlags('s')}},
    {CSR_SENVCFG,
        {"senvcfg", MISCREG_SENVCFG, rvTypeFlags(RV64, RV32),
         isaExtsFlags('s')}},

    {CSR_MVENDORID,
        {"mvendorid", MISCREG_VENDORID, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MARCHID,
        {"marchid", MISCREG_ARCHID, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MIMPID,
        {"mimpid", MISCREG_IMPID, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MHARTID,
        {"mhartid", MISCREG_HARTID, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MSTATUS,
        {"mstatus", MISCREG_STATUS, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MISA,
        {"misa", MISCREG_ISA, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MEDELEG,
        {"medeleg", MISCREG_MEDELEG, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MIDELEG,
        {"mideleg", MISCREG_MIDELEG, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MIE,
        {"mie", MISCREG_IE, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MTVEC,
        {"mtvec", MISCREG_MTVEC, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MCOUNTEREN,
        {"mcounteren", MISCREG_MCOUNTEREN, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MSTATUSH,
        {"mstatush", MISCREG_MSTATUSH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_MSCRATCH,
        {"mscratch", MISCREG_MSCRATCH, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MEPC,
        {"mepc", MISCREG_MEPC, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MCAUSE,
        {"mcause", MISCREG_MCAUSE, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MTVAL,
        {"mtval", MISCREG_MTVAL, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MIP,
        {"mip", MISCREG_IP, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_PMPCFG0,
        {"pmpcfg0", MISCREG_PMPCFG0, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    // pmpcfg1 rv32 only
    {CSR_PMPCFG1,
        {"pmpcfg1", MISCREG_PMPCFG1, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_PMPCFG2,
        {"pmpcfg2", MISCREG_PMPCFG2, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    // pmpcfg3 rv32 only
    {CSR_PMPCFG3,
        {"pmpcfg3", MISCREG_PMPCFG3, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_PMPADDR00,
        {"pmpaddr0", MISCREG_PMPADDR00, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR01,
        {"pmpaddr1", MISCREG_PMPADDR01, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR02,
        {"pmpaddr2", MISCREG_PMPADDR02, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR03,
        {"pmpaddr3", MISCREG_PMPADDR03, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR04,
        {"pmpaddr4", MISCREG_PMPADDR04, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR05,
        {"pmpaddr5", MISCREG_PMPADDR05, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR06,
        {"pmpaddr6", MISCREG_PMPADDR06, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR07,
        {"pmpaddr7", MISCREG_PMPADDR07, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR08,
        {"pmpaddr8", MISCREG_PMPADDR08, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR09,
        {"pmpaddr9", MISCREG_PMPADDR09, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR10,
        {"pmpaddr10", MISCREG_PMPADDR10, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR11,
        {"pmpaddr11", MISCREG_PMPADDR11, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR12,
        {"pmpaddr12", MISCREG_PMPADDR12, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR13,
        {"pmpaddr13", MISCREG_PMPADDR13, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR14,
        {"pmpaddr14", MISCREG_PMPADDR14, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_PMPADDR15,
        {"pmpaddr15", MISCREG_PMPADDR15, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MCYCLE,
        {"mcycle", MISCREG_CYCLE, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_MINSTRET,
        {"minstret", MISCREG_INSTRET, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER03,
        {"mhpmcounter03", MISCREG_HPMCOUNTER03, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER04,
        {"mhpmcounter04", MISCREG_HPMCOUNTER04, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER05,
        {"mhpmcounter05", MISCREG_HPMCOUNTER05, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER06,
        {"mhpmcounter06", MISCREG_HPMCOUNTER06, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER07,
        {"mhpmcounter07", MISCREG_HPMCOUNTER07, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER08,
        {"mhpmcounter08", MISCREG_HPMCOUNTER08, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER09,
        {"mhpmcounter09", MISCREG_HPMCOUNTER09, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER10,
        {"mhpmcounter10", MISCREG_HPMCOUNTER10, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER11,
        {"mhpmcounter11", MISCREG_HPMCOUNTER11, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER12,
        {"mhpmcounter12", MISCREG_HPMCOUNTER12, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER13,
        {"mhpmcounter13", MISCREG_HPMCOUNTER13, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER14,
        {"mhpmcounter14", MISCREG_HPMCOUNTER14, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER15,
        {"mhpmcounter15", MISCREG_HPMCOUNTER15, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER16,
        {"mhpmcounter16", MISCREG_HPMCOUNTER16, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER17,
        {"mhpmcounter17", MISCREG_HPMCOUNTER17, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER18,
        {"mhpmcounter18", MISCREG_HPMCOUNTER18, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER19,
        {"mhpmcounter19", MISCREG_HPMCOUNTER19, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER20,
        {"mhpmcounter20", MISCREG_HPMCOUNTER20, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER21,
        {"mhpmcounter21", MISCREG_HPMCOUNTER21, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER22,
        {"mhpmcounter22", MISCREG_HPMCOUNTER22, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER23,
        {"mhpmcounter23", MISCREG_HPMCOUNTER23, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER24,
        {"mhpmcounter24", MISCREG_HPMCOUNTER24, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER25,
        {"mhpmcounter25", MISCREG_HPMCOUNTER25, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER26,
        {"mhpmcounter26", MISCREG_HPMCOUNTER26, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER27,
        {"mhpmcounter27", MISCREG_HPMCOUNTER27, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER28,
        {"mhpmcounter28", MISCREG_HPMCOUNTER28, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER29,
        {"mhpmcounter29", MISCREG_HPMCOUNTER29, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER30,
        {"mhpmcounter30", MISCREG_HPMCOUNTER30, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER31,
        {"mhpmcounter31", MISCREG_HPMCOUNTER31, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},

    {CSR_MCYCLEH,
        {"mcycleh", MISCREG_CYCLEH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_MINSTRETH,
        {"minstreth", MISCREG_INSTRETH, rvTypeFlags(RV32), isaExtsFlags()}},
    {CSR_MHPMCOUNTER03H,
        {"mhpmcounter03h", MISCREG_HPMCOUNTER03H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER04H,
        {"mhpmcounter04h", MISCREG_HPMCOUNTER04H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER05H,
        {"mhpmcounter05h", MISCREG_HPMCOUNTER05H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER06H,
        {"mhpmcounter06h", MISCREG_HPMCOUNTER06H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER07H,
        {"mhpmcounter07h", MISCREG_HPMCOUNTER07H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER08H,
        {"mhpmcounter08h", MISCREG_HPMCOUNTER08H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER09H,
        {"mhpmcounter09h", MISCREG_HPMCOUNTER09H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER10H,
        {"mhpmcounter10h", MISCREG_HPMCOUNTER10H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER11H,
        {"mhpmcounter11h", MISCREG_HPMCOUNTER11H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER12H,
        {"mhpmcounter12h", MISCREG_HPMCOUNTER12H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER13H,
        {"mhpmcounter13h", MISCREG_HPMCOUNTER13H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER14H,
        {"mhpmcounter14h", MISCREG_HPMCOUNTER14H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER15H,
        {"mhpmcounter15h", MISCREG_HPMCOUNTER15H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER16H,
        {"mhpmcounter16h", MISCREG_HPMCOUNTER16H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER17H,
        {"mhpmcounter17h", MISCREG_HPMCOUNTER17H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER18H,
        {"mhpmcounter18h", MISCREG_HPMCOUNTER18H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER19H,
        {"mhpmcounter19h", MISCREG_HPMCOUNTER19H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER20H,
        {"mhpmcounter20h", MISCREG_HPMCOUNTER20H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER21H,
        {"mhpmcounter21h", MISCREG_HPMCOUNTER21H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER22H,
        {"mhpmcounter22h", MISCREG_HPMCOUNTER22H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER23H,
        {"mhpmcounter23h", MISCREG_HPMCOUNTER23H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER24H,
        {"mhpmcounter24h", MISCREG_HPMCOUNTER24H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER25H,
        {"mhpmcounter25h", MISCREG_HPMCOUNTER25H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER26H,
        {"mhpmcounter26h", MISCREG_HPMCOUNTER26H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER27H,
        {"mhpmcounter27h", MISCREG_HPMCOUNTER27H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER28H,
        {"mhpmcounter28h", MISCREG_HPMCOUNTER28H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER29H,
        {"mhpmcounter29h", MISCREG_HPMCOUNTER29H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER30H,
        {"mhpmcounter30h", MISCREG_HPMCOUNTER30H, rvTypeFlags(RV32),
         isaExtsFlags()}},
    {CSR_MHPMCOUNTER31H,
        {"mhpmcounter31h", MISCREG_HPMCOUNTER31H, rvTypeFlags(RV32),
         isaExtsFlags()}},

    {CSR_MHPMEVENT03,
        {"mhpmevent03", MISCREG_HPMEVENT03, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT04,
        {"mhpmevent04", MISCREG_HPMEVENT04, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT05,
        {"mhpmevent05", MISCREG_HPMEVENT05, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT06,
        {"mhpmevent06", MISCREG_HPMEVENT06, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT07,
        {"mhpmevent07", MISCREG_HPMEVENT07, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT08,
        {"mhpmevent08", MISCREG_HPMEVENT08, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT09,
        {"mhpmevent09", MISCREG_HPMEVENT09, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT10,
        {"mhpmevent10", MISCREG_HPMEVENT10, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT11,
        {"mhpmevent11", MISCREG_HPMEVENT11, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT12,
        {"mhpmevent12", MISCREG_HPMEVENT12, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT13,
        {"mhpmevent13", MISCREG_HPMEVENT13, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT14,
        {"mhpmevent14", MISCREG_HPMEVENT14, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT15,
        {"mhpmevent15", MISCREG_HPMEVENT15, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT16,
        {"mhpmevent16", MISCREG_HPMEVENT16, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT17,
        {"mhpmevent17", MISCREG_HPMEVENT17, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT18,
        {"mhpmevent18", MISCREG_HPMEVENT18, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT19,
        {"mhpmevent19", MISCREG_HPMEVENT19, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT20,
        {"mhpmevent20", MISCREG_HPMEVENT20, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT21,
        {"mhpmevent21", MISCREG_HPMEVENT21, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT22,
        {"mhpmevent22", MISCREG_HPMEVENT22, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT23,
        {"mhpmevent23", MISCREG_HPMEVENT23, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT24,
        {"mhpmevent24", MISCREG_HPMEVENT24, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT25,
        {"mhpmevent25", MISCREG_HPMEVENT25, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT26,
        {"mhpmevent26", MISCREG_HPMEVENT26, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT27,
        {"mhpmevent27", MISCREG_HPMEVENT27, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT28,
        {"mhpmevent28", MISCREG_HPMEVENT28, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT29,
        {"mhpmevent29", MISCREG_HPMEVENT29, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT30,
        {"mhpmevent30", MISCREG_HPMEVENT30, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},
    {CSR_MHPMEVENT31,
        {"mhpmevent31", MISCREG_HPMEVENT31, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},

    {CSR_TSELECT,
        {"tselect", MISCREG_TSELECT, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_TDATA1,
        {"tdata1", MISCREG_TDATA1, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_TDATA2,
        {"tdata2", MISCREG_TDATA2, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_TDATA3,
        {"tdata3", MISCREG_TDATA3, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_DCSR,
        {"dcsr", MISCREG_DCSR, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_DPC,
        {"dpc", MISCREG_DPC, rvTypeFlags(RV64, RV32), isaExtsFlags()}},
    {CSR_DSCRATCH,
        {"dscratch", MISCREG_DSCRATCH, rvTypeFlags(RV64, RV32),
         isaExtsFlags()}},

    {CSR_VSTART,
        {"vstart", MISCREG_VSTART, rvTypeFlags(RV64, RV32),
         isaExtsFlags('v')}},
    {CSR_VXSAT,
        {"vxsat", MISCREG_VXSAT, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},
    {CSR_VXRM,
        {"vxrm", MISCREG_VXRM, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},
    {CSR_VCSR,
        {"vcsr", MISCREG_VCSR, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},
    {CSR_VL,
        {"vl", MISCREG_VL, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},
    {CSR_VTYPE,
        {"vtype", MISCREG_VTYPE, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},
    {CSR_VLENB,
        {"VLENB", MISCREG_VLENB, rvTypeFlags(RV64, RV32), isaExtsFlags('v')}},

    {CSR_MNSCRATCH,
        {"mnscratch", MISCREG_MNSCRATCH, rvTypeFlags(RV64, RV32),
         isaExtsFlags(), true}},
    {CSR_MNEPC,
        {"mnepc", MISCREG_MNEPC, rvTypeFlags(RV64, RV32), isaExtsFlags(),
         true}},
    {CSR_MNCAUSE,
        {"mncause", MISCREG_MNCAUSE, rvTypeFlags(RV64, RV32), isaExtsFlags(),
         true}},
    {CSR_MNSTATUS,
        {"mnstatus", MISCREG_MNSTATUS, rvTypeFlags(RV64, RV32),
         isaExtsFlags(), true}},

    {CSR_JVT,
        {"jvt", MISCREG_JVT, rvTypeFlags(RV64, RV32), isaExtsFlags()}},

    // H-extension CSR -> MISCREG mappings
    {CSR_MTINST,
        {"mtinst", MISCREG_MTINST, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_MTVAL2,
        {"mtval2", MISCREG_MTVAL2, rvTypeFlags(RV64),
        isaExtsFlags('h')}},

    {CSR_HSTATUS,
        {"hstatus", MISCREG_HSTATUS, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HEDELEG,
        {"hedeleg", MISCREG_HEDELEG, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HIDELEG,
        {"hideleg", MISCREG_HIDELEG, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HIE,
        {"hie", MISCREG_IE, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HCOUNTEREN,
        {"hcounteren", MISCREG_HCOUNTEREN, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HGEIE,
        {"hgeie", MISCREG_HGEIE, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HTVAL,
        {"htval", MISCREG_HTVAL, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HIP,
        {"hip", MISCREG_IP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HVIP,
        {"hvip", MISCREG_HVIP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HTINST,
        {"htinst", MISCREG_HTINST, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HGEIP,
        {"hgeip", MISCREG_HGEIP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HENVCFG,
        {"henvcfg", MISCREG_HENVCFG, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HGATP,
        {"hgatp", MISCREG_HGATP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HCONTEXT,
        {"hcontext", MISCREG_HCONTEXT, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_HTIMEDELTA,
        {"htimedelta", MISCREG_HTIMEDELTA, rvTypeFlags(RV64),
        isaExtsFlags('h')}},

    {CSR_VSSTATUS,
        {"vsstatus", MISCREG_VSSTATUS, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSIE,
        {"vsie", MISCREG_IE, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSTVEC,
        {"vstvec", MISCREG_VSTVEC, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSSCRATCH,
        {"vsscratch", MISCREG_VSSCRATCH, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSEPC,
        {"vsepc", MISCREG_VSEPC, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSCAUSE,
        {"vscause", MISCREG_VSCAUSE, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSTVAL,
        {"vstval", MISCREG_VSTVAL, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSIP,
        {"vsip", MISCREG_IP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
    {CSR_VSATP,
        {"vsatp", MISCREG_VSATP, rvTypeFlags(RV64),
        isaExtsFlags('h')}},
};

/**
 * These fields are specified in the RISC-V Instruction Set Manual, Volume II,
 * v1.10, accessible at www.riscv.org. in Figure 3.7. The main register that
 * uses these fields is the MSTATUS register, which is shadowed by two others
 * accessible at lower privilege levels (SSTATUS and USTATUS) that can't see
 * the fields for higher privileges.
 */
BitUnion64(STATUS)
    Bitfield<63> rv64_sd;
    Bitfield<39> mpv; // H-extension
    Bitfield<38> gva; // H-extension
    Bitfield<37> mbe;
    Bitfield<36> sbe;
    Bitfield<35, 34> sxl;
    Bitfield<33, 32> uxl;
    Bitfield<31> rv32_sd;
    Bitfield<22> tsr;
    Bitfield<21> tw;
    Bitfield<20> tvm;
    Bitfield<19> mxr;
    Bitfield<18> sum;
    Bitfield<17> mprv;
    Bitfield<16, 15> xs;
    Bitfield<14, 13> fs;
    Bitfield<12, 11> mpp;
    Bitfield<10, 9> vs;
    Bitfield<8> spp;
    Bitfield<7> mpie;
    Bitfield<6> ube;
    Bitfield<5> spie;
    Bitfield<3> mie;
    Bitfield<1> sie;
EndBitUnion(STATUS)


// H-extension
BitUnion64(HSTATUS)
    Bitfield<33, 32> vsxl;
    Bitfield<22> vtsr;
    Bitfield<21> vtw;
    Bitfield<20> vtvm;
    Bitfield<17, 12> vgein;
    Bitfield<9> hu;
    Bitfield<8> spvp;
    Bitfield<7> spv;
    Bitfield<6> gva;
    Bitfield<5> vsbe;
EndBitUnion(HSTATUS)


/**
 * These fields are specified in the RISC-V Instruction Set Manual.
 * Resumable Non-Maskable Interrupts. The main register that
 * uses these fields is the MNSTATUS register
 */
BitUnion64(NSTATUS)
    Bitfield<12, 11> mnpp;
    Bitfield<7> mnv;
    Bitfield<3> nmie;
EndBitUnion(NSTATUS)

/**
 * These fields are specified in the RISC-V Instruction Set Manual, Volume II,
 * v1.10, v1.11 and v1.12 in Figure 3.1, accessible at www.riscv.org.
 * The register is used to control instruction extensions.
 */
BitUnion64(MISA)
    Bitfield<63, 62> rv64_mxl;
    Bitfield<31, 30> rv32_mxl;
    Bitfield<23> rvx;
    Bitfield<21> rvv;
    Bitfield<20> rvu;
    Bitfield<19> rvt;
    Bitfield<18> rvs;
    Bitfield<16> rvq;
    Bitfield<15> rvp;
    Bitfield<13> rvn;
    Bitfield<12> rvm;
    Bitfield<11> rvl;
    Bitfield<10> rvk;
    Bitfield<9> rvj;
    Bitfield<8> rvi;
    Bitfield<7> rvh;
    Bitfield<6> rvg;
    Bitfield<5> rvf;
    Bitfield<4> rve;
    Bitfield<3> rvd;
    Bitfield<2> rvc;
    Bitfield<1> rvb;
    Bitfield<0> rva;
EndBitUnion(MISA)

/**
 * These fields are specified in the RISC-V Instruction Set Manual, Volume II,
 * v1.10 in Figures 3.11 and 3.12, accessible at www.riscv.org. Both the MIP
 * and MIE registers have the same fields, so accesses to either should use
 * this bit union.
 */
BitUnion64(INTERRUPT)
    Bitfield<63,16> local;
    Bitfield<12> sgei; // H-extension
    Bitfield<11> mei;
    Bitfield<10> vsei; // H-extension
    Bitfield<9> sei;
    Bitfield<7> mti;
    Bitfield<6> vsti;  // H-extension
    Bitfield<5> sti;
    Bitfield<3> msi;
    Bitfield<2> vssi;  // H-extension
    Bitfield<1> ssi;
EndBitUnion(INTERRUPT)


// From the RISCV specification version 20240411, volume 2,
// section 10.1.10, page 98
BitUnion64(SENVCFG)
    Bitfield<63,34> wpri_1;
    Bitfield<33,32> pmm;
    Bitfield<31,8> wpri_2;
    Bitfield<7> cbze;
    Bitfield<6> cbcfe;
    Bitfield<5,4> cbie;
    Bitfield<3,1> wpri_3;
    Bitfield<0> fiom;
EndBitUnion(SENVCFG)

BitUnion64(JVT)
    Bitfield<63,6> base;
    Bitfield<5,0> mode;
EndBitUnion(JVT)

const off_t MXL_OFFSETS[enums::Num_RiscvType] = {
    [RV32] = (sizeof(uint32_t) * 8 - 2),
    [RV64] = (sizeof(uint64_t) * 8 - 2),
};
const off_t MBE_OFFSET[enums::Num_RiscvType] = {
    [RV32] = 5,
    [RV64] = 37,
};
const off_t SBE_OFFSET[enums::Num_RiscvType] = {
    [RV32] = 4,
    [RV64] = 36,
};
const off_t SXL_OFFSET = 34;
const off_t VSXL_OFFSET = 32; // H-extension
const off_t UXL_OFFSET = 32;
const off_t FS_OFFSET = 13;
const off_t VS_OFFSET = 9;
const off_t FRM_OFFSET = 5;

const RegVal ISA_MXL_MASKS[enums::Num_RiscvType] = {
    [RV32] = 3ULL << MXL_OFFSETS[RV32],
    [RV64] = 3ULL << MXL_OFFSETS[RV64],
};
const RegVal ISA_EXT_MASK = mask(26);
const RegVal ISA_EXT_C_MASK = 1UL << ('c' - 'a');
const RegVal MISA_MASKS[enums::Num_RiscvType] = {
    [RV32] = ISA_MXL_MASKS[RV32] | ISA_EXT_MASK,
    [RV64] = ISA_MXL_MASKS[RV64] | ISA_EXT_MASK,
};


const RegVal STATUS_SD_MASKS[enums::Num_RiscvType] = {
    [RV32] = 1ULL << ((sizeof(uint32_t) * 8) - 1),
    [RV64] = 1ULL << ((sizeof(uint64_t) * 8) - 1),
};
const RegVal STATUS_MBE_MASK[enums::Num_RiscvType] = {
    [RV32] = 1ULL << MBE_OFFSET[RV32],
    [RV64] = 1ULL << MBE_OFFSET[RV64],
};
const RegVal STATUS_SBE_MASK[enums::Num_RiscvType] = {
    [RV32] = 1ULL << SBE_OFFSET[RV32],
    [RV64] = 1ULL << SBE_OFFSET[RV64],
};
// These first two offsets only work for RV64
const RegVal STATUS_MPV_MASK = 1LL << 39; // H-extension
const RegVal STATUS_GVA_MASK = 1LL << 38; // H-extension
const RegVal STATUS_SXL_MASK = 3ULL << SXL_OFFSET;
const RegVal STATUS_UXL_MASK = 3ULL << UXL_OFFSET;
const RegVal STATUS_TSR_MASK = 1ULL << 22;
const RegVal STATUS_TW_MASK = 1ULL << 21;
const RegVal STATUS_TVM_MASK = 1ULL << 20;
const RegVal STATUS_MXR_MASK = 1ULL << 19;
const RegVal STATUS_SUM_MASK = 1ULL << 18;
const RegVal STATUS_MPRV_MASK = 1ULL << 17;
const RegVal STATUS_XS_MASK = 3ULL << 15;
const RegVal STATUS_FS_MASK = 3ULL << FS_OFFSET;
const RegVal STATUS_MPP_MASK = 3ULL << 11;
const RegVal STATUS_VS_MASK = 3ULL << VS_OFFSET;
const RegVal STATUS_SPP_MASK = 1ULL << 8;
const RegVal STATUS_MPIE_MASK = 1ULL << 7;
const RegVal STATUS_UBE_MASK = 1ULL << 6;
const RegVal STATUS_SPIE_MASK = 1ULL << 5;
const RegVal STATUS_MIE_MASK = 1ULL << 3;
const RegVal STATUS_SIE_MASK = 1ULL << 1;

// H-extension
const RegVal HSTATUS_VSXL_MASK = 3ULL << VSXL_OFFSET;
const RegVal HSTATUS_VTSR_MASK = 1ULL << 22;
const RegVal HSTATUS_VTW_MASK = 1ULL << 21;
const RegVal HSTATUS_VTVM_MASK = 1ULL << 20;
const RegVal HSTATUS_VGEIN_MASK = 63ULL << 12;
const RegVal HSTATUS_HU_MASK = 1ULL << 9;
const RegVal HSTATUS_SPVP_MASK = 1ULL << 8;
const RegVal HSTATUS_SPV_MASK = 1ULL << 7;
const RegVal HSTATUS_GVA_MASK = 1LL << 6;
const RegVal HSTATUS_VSBE_MASK = 1ULL << 5;

const RegVal
MSTATUS_MASKS[enums::Num_RiscvType][enums::Num_PrivilegeModeSet] = {
    [RV32] = {
        [enums::M] = STATUS_SD_MASKS[RV32] |
                     STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                     STATUS_MPIE_MASK | STATUS_MIE_MASK,
        [enums::MU] = STATUS_SD_MASKS[RV32] | STATUS_TW_MASK  |
                      STATUS_MPRV_MASK |
                      STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                      STATUS_MPP_MASK | STATUS_MPIE_MASK | STATUS_MIE_MASK,
        [enums::MSU] = STATUS_SD_MASKS[RV32] | STATUS_TSR_MASK |
                       STATUS_TW_MASK | STATUS_TVM_MASK | STATUS_MXR_MASK |
                       STATUS_SUM_MASK | STATUS_MPRV_MASK |
                       STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                       STATUS_MPP_MASK | STATUS_SPP_MASK |
                       STATUS_MPIE_MASK | STATUS_SPIE_MASK |
                       STATUS_MIE_MASK | STATUS_SIE_MASK,
    },
    [RV64] = {
        [enums::M] = STATUS_SD_MASKS[RV64] | STATUS_MBE_MASK[RV64] |
                     STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                     STATUS_MPIE_MASK | STATUS_MIE_MASK,
        [enums::MU] = STATUS_SD_MASKS[RV64] | STATUS_MBE_MASK[RV64] |
                      STATUS_UXL_MASK | STATUS_TW_MASK |  STATUS_MPRV_MASK |
                      STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                      STATUS_MPP_MASK | STATUS_MPIE_MASK | STATUS_MIE_MASK,
        [enums::MSU] = STATUS_SD_MASKS[RV64] |
                       STATUS_MBE_MASK[RV64] | STATUS_SBE_MASK[RV64] |
                       STATUS_SXL_MASK | STATUS_UXL_MASK |
                       STATUS_TSR_MASK | STATUS_TW_MASK | STATUS_TVM_MASK |
                       STATUS_MXR_MASK | STATUS_SUM_MASK | STATUS_MPRV_MASK |
                       STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                       STATUS_MPP_MASK | STATUS_SPP_MASK |
                       STATUS_MPIE_MASK | STATUS_SPIE_MASK |
                       STATUS_MIE_MASK | STATUS_SIE_MASK,
        [enums::MHSU] = STATUS_SD_MASKS[RV64] |
                       STATUS_MPV_MASK | STATUS_GVA_MASK | // H-extension
                       STATUS_MBE_MASK[RV64] | STATUS_SBE_MASK[RV64] |
                       STATUS_SXL_MASK | STATUS_UXL_MASK |
                       STATUS_TSR_MASK | STATUS_TW_MASK | STATUS_TVM_MASK |
                       STATUS_MXR_MASK | STATUS_SUM_MASK | STATUS_MPRV_MASK |
                       STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                       STATUS_MPP_MASK | STATUS_SPP_MASK |
                       STATUS_MPIE_MASK | STATUS_SPIE_MASK |
                       STATUS_MIE_MASK | STATUS_SIE_MASK,
    },
};
// rv32 only
const RegVal MSTATUSH_MASKS[enums::Num_PrivilegeModeSet] = {
    [enums::M] = STATUS_MBE_MASK[RV32],
    [enums::MU] = STATUS_MBE_MASK[RV32],
    [enums::MSU] = STATUS_MBE_MASK[RV32] | STATUS_SBE_MASK[RV32],
};

const RegVal
HSTATUS_MASKS[enums::Num_RiscvType][enums::Num_PrivilegeModeSet] = {
    [RV32] = {
        [enums::M] = 0ULL,
        [enums::MU] = 0ULL,
        [enums::MSU] = 0ULL,
        [enums::MHSU] = 0ULL,
    },
    [RV64] = {
        [enums::M] = 0ULL,
        [enums::MU] = 0ULL,
        [enums::MSU] = 0ULL,
        [enums::MHSU] = HSTATUS_VSXL_MASK | HSTATUS_VTSR_MASK |
                        HSTATUS_VTW_MASK   | HSTATUS_VTVM_MASK |
                        HSTATUS_VGEIN_MASK | HSTATUS_HU_MASK |
                        HSTATUS_SPVP_MASK | HSTATUS_SPV_MASK |
                        HSTATUS_GVA_MASK | HSTATUS_VSBE_MASK,
    },
};
const RegVal
SSTATUS_MASKS[enums::Num_RiscvType][enums::Num_PrivilegeModeSet] = {
    [RV32] = {
        [enums::M] = 0ULL,
        [enums::MU] = 0ULL,
        [enums::MSU] = STATUS_SD_MASKS[RV32] | STATUS_MXR_MASK |
                       STATUS_SUM_MASK |
                       STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                       STATUS_SPP_MASK | STATUS_SPIE_MASK | STATUS_SIE_MASK,
    },
    [RV64] = {
        [enums::M] = 0ULL,
        [enums::MU] = 0ULL,
        [enums::MSU] = STATUS_SD_MASKS[RV64] | STATUS_UXL_MASK |
                       STATUS_MXR_MASK | STATUS_SUM_MASK |
                       STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                       STATUS_SPP_MASK | STATUS_SPIE_MASK | STATUS_SIE_MASK,
        [enums::MHSU] = STATUS_SD_MASKS[RV64] | STATUS_UXL_MASK |
                        STATUS_MXR_MASK | STATUS_SUM_MASK | STATUS_UBE_MASK |
                        STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                        STATUS_SPP_MASK | STATUS_SPIE_MASK | STATUS_SIE_MASK,
    },
};

const RegVal LOCAL_MASK = mask(63,16);
const RegVal SGEI_MASK = 1ULL << 12; // H-extension
const RegVal MEI_MASK = 1ULL << 11;
const RegVal VSEI_MASK = 1ULL << 10; // H-extension
const RegVal SEI_MASK = 1ULL << 9;
const RegVal MTI_MASK = 1ULL << 7;
const RegVal VSTI_MASK = 1ULL << 6; // H-extension
const RegVal STI_MASK = 1ULL << 5;
const RegVal MSI_MASK = 1ULL << 3;
const RegVal VSSI_MASK = 1ULL << 2; // H-extension
const RegVal SSI_MASK = 1ULL << 1;

const RegVal MI_MASK[enums::Num_PrivilegeModeSet] = {
    [enums::M] = LOCAL_MASK |
                 MEI_MASK| MTI_MASK | MSI_MASK,
    [enums::MU] = LOCAL_MASK |
                  MEI_MASK| MTI_MASK | MSI_MASK,
    [enums::MSU] = LOCAL_MASK |
                   MEI_MASK | SEI_MASK |
                   MTI_MASK | STI_MASK |
                   MSI_MASK | SSI_MASK,
    [enums::MHSU] = LOCAL_MASK |
                    MEI_MASK | VSEI_MASK | SEI_MASK |
                    MTI_MASK | VSTI_MASK | STI_MASK |
                    MSI_MASK | VSSI_MASK | SSI_MASK | SGEI_MASK,
};

const RegVal SI_MASK[enums::Num_PrivilegeModeSet] = {
    [enums::M] = LOCAL_MASK,
    [enums::MU] = LOCAL_MASK,
    [enums::MSU] = LOCAL_MASK | SEI_MASK | STI_MASK | SSI_MASK,
    [enums::MHSU] = LOCAL_MASK | SEI_MASK | STI_MASK | SSI_MASK,
};
const RegVal MIDELEG_MASK[enums::Num_PrivilegeModeSet] = {
    [enums::M] = LOCAL_MASK,
    [enums::MU] = LOCAL_MASK,
    [enums::MSU] = LOCAL_MASK | SEI_MASK | STI_MASK | SSI_MASK,
    [enums::MHSU] = LOCAL_MASK | SEI_MASK | STI_MASK | SSI_MASK,
};

const RegVal VSI_MASK[enums::Num_PrivilegeModeSet] = {
    [enums::M] = LOCAL_MASK,
    [enums::MU] = LOCAL_MASK,
    [enums::MSU] = LOCAL_MASK,
    [enums::MHSU] = LOCAL_MASK | VSEI_MASK | VSTI_MASK | VSSI_MASK,
};

const RegVal FFLAGS_MASK = (1 << FRM_OFFSET) - 1;
const RegVal FRM_MASK = 0x7;

const RegVal CAUSE_INTERRUPT_MASKS[enums::Num_RiscvType] = {
    [RV32] = (1ULL << 31),
    [RV64] = (1ULL << 63),
};


// H-extension
const RegVal DELEGABLE_INTS_MASK = SSI_MASK | STI_MASK | SEI_MASK |
                                   VSSI_MASK | VSTI_MASK | VSEI_MASK;
// H-extension
const RegVal HS_INTERRUPTS = SGEI_MASK | VSSI_MASK | VSTI_MASK | VSEI_MASK;

const std::unordered_map<int, RegVal>
CSRMasks[enums::Num_RiscvType][enums::Num_PrivilegeModeSet] = {
    [RV32] = {
        [enums::M] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV32][enums::M]},
            {CSR_SIE, SI_MASK[enums::M]},
            {CSR_SIP, SI_MASK[enums::M]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV32][enums::M]},
            {CSR_MISA, MISA_MASKS[RV32]},
            {CSR_MIE, MI_MASK[enums::M]},
            {CSR_MSTATUSH, MSTATUSH_MASKS[enums::M]},
            {CSR_MIP, MI_MASK[enums::M]},
        },
        [enums::MU] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV32][enums::MU]},
            {CSR_SIE, SI_MASK[enums::MU]},
            {CSR_SIP, SI_MASK[enums::MU]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV32][enums::MU]},
            {CSR_MISA, MISA_MASKS[RV32]},
            {CSR_MIE, MI_MASK[enums::MU]},
            {CSR_MSTATUSH, MSTATUSH_MASKS[enums::MU]},
            {CSR_MIP, MI_MASK[enums::MU]},
        },
        [enums::MSU] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV32][enums::MSU]},
            {CSR_SIE, SI_MASK[enums::MSU]},
            {CSR_SIP, SI_MASK[enums::MSU]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV32][enums::MSU]},
            {CSR_MISA, MISA_MASKS[RV32]},
            {CSR_MIE, MI_MASK[enums::MSU]},
            {CSR_MSTATUSH, MSTATUSH_MASKS[enums::MSU]},
            {CSR_MIP, MI_MASK[enums::MSU]},
        },
    },
    [RV64] = {
        [enums::M] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV64][enums::M]},
            {CSR_SIE, SI_MASK[enums::M]},
            {CSR_SIP, SI_MASK[enums::M]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV64][enums::M]},
            {CSR_MISA, MISA_MASKS[RV64]},
            {CSR_MIE, MI_MASK[enums::M]},
            {CSR_MIP, MI_MASK[enums::M]},
        },
        [enums::MU] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV64][enums::MU]},
            {CSR_SIE, SI_MASK[enums::MU]},
            {CSR_SIP, SI_MASK[enums::MU]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV64][enums::MU]},
            {CSR_MISA, MISA_MASKS[RV64]},
            {CSR_MIE, MI_MASK[enums::MU]},
            {CSR_MIP, MI_MASK[enums::MU]},
        },
        [enums::MSU] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV64][enums::MSU]},
            {CSR_SIE, SI_MASK[enums::MSU]},
            {CSR_SIP, SI_MASK[enums::MSU]},
            {CSR_MSTATUS, MSTATUS_MASKS[RV64][enums::MSU]},
            {CSR_MISA, MISA_MASKS[RV64]},
            {CSR_MIE, MI_MASK[enums::MSU]},
            {CSR_MIP, MI_MASK[enums::MSU]},
        },
        [enums::MHSU] = {
            {CSR_FFLAGS, FFLAGS_MASK},
            {CSR_FRM, FRM_MASK},
            {CSR_FCSR, FFLAGS_MASK | (FRM_MASK << FRM_OFFSET)},
            {CSR_SSTATUS, SSTATUS_MASKS[RV64][enums::MHSU]},
            {CSR_SIE, SI_MASK[enums::MHSU]},
            {CSR_SIP, SI_MASK[enums::MHSU]},
            {CSR_VSSTATUS, SSTATUS_MASKS[RV64][enums::MHSU]},
            {CSR_VSIE, VSI_MASK[enums::MHSU]},
            {CSR_VSIP, VSI_MASK[enums::MHSU]},
            {CSR_HSTATUS, HSTATUS_MASKS[RV64][enums::MHSU]},
            {CSR_HIE, HS_INTERRUPTS},
            {CSR_HIP, HS_INTERRUPTS},
            {CSR_HVIP, HS_INTERRUPTS & ~SGEI_MASK},
            {CSR_MSTATUS, MSTATUS_MASKS[RV64][enums::MHSU]},
            {CSR_MISA, MISA_MASKS[RV64]},
            {CSR_MIE, MI_MASK[enums::MHSU]},
            {CSR_MIP, MI_MASK[enums::MHSU]},
        },
    },
};


// Write masks are needed since some visible (readable)
// register bits can be read-only.
// Without using a write mask, writes are permitted to
// bits that should be read-only.

// Normal software (e.g. a linux kernel) wouldn't do this,
// but our "hardware" shouldn't allow this to any program.

// For RV32 we leave the write masks the same as the
// "visible bits" masks that are defined above for now

// Moreover, instead of writing out a write mask for
// every register, we only specify masks for registers
// whose write mask differs from the total visible bits.
// This saves space and improves readability.
// To use the map we lookup a CSR for its write-mask
// If the mask is present it is used, otherwise the write mask
// that should be used is the "visible bits" mask define above.

// clang-format off
const std::unordered_map<int, RegVal>
CSRWriteMasks[enums::Num_RiscvType][enums::Num_PrivilegeModeSet] = {
    [RV32] = {
        [enums::M] = {
            {CSR_MIDELEG, 0ULL},
            {CSR_MEDELEG, 0ULL},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK
            },
            {CSR_MIP, LOCAL_MASK},
        },
        [enums::MU] = {
            {CSR_MIDELEG, 0ULL},
            {CSR_MEDELEG, 0ULL},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK |
                STATUS_MPRV_MASK // added for U
            },
            {CSR_MIP, LOCAL_MASK},
        },
        [enums::MSU] = {
            {CSR_MIDELEG, MIDELEG_MASK[enums::MSU]},
            {CSR_MEDELEG, DELEGABLE_EXCPS},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK  | STATUS_TVM_MASK  |
                STATUS_MPRV_MASK | // added for U
                STATUS_TSR_MASK  | STATUS_SIE_MASK | STATUS_SPIE_MASK |
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for S
            },
            {CSR_MIP,
                LOCAL_MASK |
                SEI_MASK | SSI_MASK | STI_MASK // added for S
            },
            {CSR_SSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_SIE_MASK | STATUS_SPIE_MASK | // no TSR here!
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for S
            },
            {CSR_SIP,
                LOCAL_MASK |
                SSI_MASK // added for S
            },
        },
    },
    [RV64] = {
        [enums::M] = {
            {CSR_MIDELEG, 0ULL},
            {CSR_MEDELEG, 0ULL},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK
            },
            {CSR_MIP, LOCAL_MASK},
        },
        [enums::MU] = {
            {CSR_MIDELEG, 0ULL},
            {CSR_MEDELEG, 0ULL},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK  |
                STATUS_MPRV_MASK // added for U
            },
            {CSR_MIP, LOCAL_MASK},
        },
        [enums::MSU] = {
            {CSR_MIDELEG, MIDELEG_MASK[enums::MSU]},
            {CSR_MEDELEG, DELEGABLE_EXCPS},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK  | STATUS_TVM_MASK  |
                STATUS_MPRV_MASK | // added for U
                STATUS_TSR_MASK  | STATUS_SIE_MASK | STATUS_SPIE_MASK |
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for S
            },
            {CSR_MIP,
                LOCAL_MASK |
                SEI_MASK | SSI_MASK | STI_MASK // added for S
            },
            {CSR_SSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_SIE_MASK | STATUS_SPIE_MASK | // no TSR here!
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for S
            },
            {CSR_SIP,
                LOCAL_MASK |
                SSI_MASK // added for S
            },
        },
        [enums::MHSU] = {
            {CSR_MIDELEG, MIDELEG_MASK[enums::MHSU]},
            {CSR_MEDELEG, DELEGABLE_EXCPS_WITH_RVH},
            {CSR_MSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_MIE_MASK | STATUS_MPIE_MASK | STATUS_MPP_MASK |
                STATUS_TW_MASK  | STATUS_TVM_MASK  |
                STATUS_MPRV_MASK | // added for U
                STATUS_TSR_MASK  | STATUS_SIE_MASK | STATUS_SPIE_MASK |
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK |
                // added for S
                STATUS_GVA_MASK | STATUS_MPV_MASK // added for H
            },
            {CSR_MIP,
                LOCAL_MASK |
                SEI_MASK | SSI_MASK | STI_MASK | // added for S
                VSSI_MASK // added for H
            },
            {CSR_SSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_SIE_MASK | STATUS_SPIE_MASK | // no TSR here!
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for S
            },
            {CSR_SIP,
                LOCAL_MASK |
                SSI_MASK // added for S
            },
            {CSR_HSTATUS,
                HSTATUS_VTSR_MASK | HSTATUS_VTW_MASK |
                HSTATUS_VTVM_MASK | HSTATUS_HU_MASK |
                HSTATUS_SPVP_MASK | HSTATUS_SPV_MASK |
                HSTATUS_GVA_MASK    // added for H
            },
            {CSR_HIP,
                VSSI_MASK // added for H
            },
            {CSR_HVIP,
                HS_INTERRUPTS & ~SGEI_MASK // added for H
            },
            {CSR_VSSTATUS,
                STATUS_XS_MASK | STATUS_FS_MASK | STATUS_VS_MASK |
                STATUS_SIE_MASK | STATUS_SPIE_MASK | // no TSR here!
                STATUS_SPP_MASK  | STATUS_SUM_MASK | STATUS_MXR_MASK
                // added for H
            },
            {CSR_VSIP,
                VSSI_MASK // added for H
            },
        },
    },
};
// clang-format on

} // namespace RiscvISA
} // namespace gem5

#endif // __ARCH_RISCV_REGS_MISC_HH__
